server:
  port: ${PORT:9109}

spring:
  datasource:
    url: jdbc:mysql://localhost/lithium_report_players
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: create
      ddl-auto: validate
    
lithium:
  services:
    db:
      load-test-data: false
    report:
      players:
        report-run-retry:
          max-number-of-retries: 10
        report-run-restart:
          restart-after-hours: 12
        player-fetch-count:
          fetch-players: 50
        include-accounting-checks:
          check-accounting: true

logging:
  level:
    lithium.service.report: INFO
