package lithium.service.casino;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

// @JsonFormat(shape = JsonFormat.Shape.STRING)
@AllArgsConstructor(access=AccessLevel.PRIVATE)
public enum CasinoTranType {
	CASINO_BET ("CASINO_BET", true),
	CASINO_VOID ("CASINO_VOID", false),
	CASINO_LOSS ("CASINO_LOSS", false),
	CASINO_WIN ("CASINO_WIN", false),
	CASINO_WIN_JACKPOT ("CASINO_WIN_JACKPOT", false),
	CASINO_NEGATIVE_BET ("CASINO_NEGATIVE_BET", false),
	PLAYERBALANCE ("PLAYER_BALANCE", false),
	NEGATIVE_BALANCE_ADJUST ("NEGATIVE_BALANCE_ADJUST", false),
	CASINO_BET_ROLLBACK("CASINO_BET_ROLLBACK", false),
	CASINO_WIN_ROLLBACK("CASINO_WIN_ROLLBACK", false),
	CASINO_WIN_JACKPOT_ROLLBACK("CASINO_WIN_JACKPOT_ROLLBACK", false),
	CASINO_NEGATIVE_BET_ROLLBACK ("CASINO_NEGATIVE_BET_ROLLBACK", false),
	PLAYER_BALANCE_CASINO_BONUS("PLAYER_BALANCE_CASINO_BONUS", false),
	PLAYER_BALANCE_CASINO_BONUS_PENDING("PLAYER_BALANCE_CASINO_BONUS_PENDING", false),
	TRANSFER_TO_CASINO_BONUS("TRANSFER_TO_CASINO_BONUS", false),
	TRANSFER_FROM_CASINO_BONUS("TRANSFER_FROM_CASINO_BONUS", false),
	TRANSFER_TO_CASINO_BONUS_PENDING("TRANSFER_TO_CASINO_BONUS_PENDING", false),
	TRANSFER_FROM_CASINO_BONUS_PENDING("TRANSFER_FROM_CASINO_BONUS_PENDING", false),
	CASINO_BONUS_ACTIVATE("CASINO_BONUS_ACTIVATE", false),
	CASINO_BONUS_PENDING("CASINO_BONUS_PENDING", false),
	CASINO_BONUS_CANCEL("CASINO_BONUS_CANCEL", false),
	CASINO_BONUS_EXPIRED("CASINO_BONUS_EXPIRED", false),
	CASINO_BONUS_MAXPAYOUT_EXCESS("CASINO_BONUS_MAXPAYOUT_EXCESS", false),
	CASINO_BET_FREESPIN ("CASINO_BET_FREESPIN", true),
	CASINO_BET_FREESPIN_ROLLBACK("CASINO_BET_FREESPIN_ROLLBACK", false),
	CASINO_LOSS_FREESPIN ("CASINO_LOSS_FREESPIN", false),
	CASINO_WIN_FREESPIN ("CASINO_WIN_FREESPIN", false),
	CASINO_WIN_FREESPIN_JACKPOT ("CASINO_WIN_FREESPIN_JACKPOT", false),
	CASINO_WIN_FREESPIN_ROLLBACK ("CASINO_WIN_FREESPIN_ROLLBACK", false),
	CASINO_WIN_FREESPIN_JACKPOT_ROLLBACK ("CASINO_WIN_FREESPIN_JACKPOT_ROLLBACK", false),
	TRANSFER_TO_CASINO_ESCROW("TRANSFER_TO_CASINO_ESCROW", false),
	TRANSFER_FROM_CASINO_ESCROW("TRANSFER_FROM_CASINO_ESCROW", false),
	PLAYER_BALANCE_CASINO_ESCROW("PLAYER_BALANCE_CASINO_ESCROW", false),
	CASINO_BONUS_PENDING_CANCEL("CASINO_BONUS_PENDING_CANCEL", false),
	CASINO_XP_GAIN("CASINO_XP_GAIN", false),
	VIRTUAL_BET ("VIRTUAL_BET", true),
	VIRTUAL_WIN ("VIRTUAL_WIN", false),
	VIRTUAL_LOSS ("VIRTUAL_LOSS", false),
	VIRTUAL_BET_VOID ("VIRTUAL_BET_VOIDED", false),
	VIRTUAL_FREE_BET ("VIRTUAL_FREE_BET", true),
	VIRTUAL_FREE_WIN ("VIRTUAL_FREE_WIN", false),
	VIRTUAL_FREE_LOSS ("VIRTUAL_FREE_LOSS", false),
	VIRTUAL_FREE_BET_VOID ("VIRTUAL_FREE_BET_VOIDED", false),
	SPORTS_BET ("SPORTS_BET", true),
	SPORTS_WIN ("SPORTS_WIN", false),
	SPORTS_LOSS ("SPORTS_LOSS", false),
	SPORTS_RESETTLEMENT("SPORTS_RESETTLEMENT", false),
	SPORTS_FREE_BET ("SPORTS_FREE_BET", true),
	SPORTS_FREE_WIN ("SPORTS_FREE_WIN", false),
	SPORTS_FREE_LOSS ("SPORTS_FREE_LOSS", false),
	SPORTS_FREE_RESETTLEMENT("SPORTS_FREE_RESETTLEMENT", false),
	SPORTS_DEBIT ("SPORTS_DEBIT", false),
	SPORTS_RESERVE ("SPORTS_RESERVE", false),
	SPORTS_RESERVE_CANCEL ("SPORTS_RESERVE_CANCEL", false),
	SPORTS_RESERVE_COMMIT ("SPORTS_RESERVE_RETURN", false),
	JACKPOT_ACCRUAL("JACKPOT_ACCRUAL", false),
	JACKPOT_ACCRUAL_CANCEL("JACKPOT_ACCRUAL_CANCEL", false),
	PLAYER_JACKPOT_ACCRUALS("PLAYER_JACKPOT_ACCRUALS", false),
	CASINO_ADHOC_CREDIT("CASINO_ADHOC_CREDIT", false),
	CASINO_ADHOC_DEBIT("CASINO_ADHOC_DEBIT", true),

	PLAYER_BALANCE_FREEGAME("PLAYER_BALANCE_FREEGAME", false),
	PLAYER_BALANCE_OPERATOR_MIGRATION("PLAYER_BALANCE_OPERATOR_MIGRATION", false),
	CASINO_BET_FREEGAME ("CASINO_BET_FREEGAME", true),
	CASINO_BET_FREEGAME_ROLLBACK ("CASINO_BET_FREEGAME_ROLLBACK", false),
	CASINO_WIN_FREEGAME ("CASINO_WIN_FREEGAME", false),
	CASINO_WIN_FREEGAME_ROLLBACK ("CASINO_WIN_FREEGAME_ROLLBACK", false),
	CASINO_LOSS_FREEGAME ("CASINO_LOSS_FREEGAME", false),

	//TODO: This should not live here.... Riaan
	REWARD_BET ("REWARD_BET", true),
	REWARD_LOSS ("REWARD_LOSS", false),
	REWARD_WIN ("REWARD_WIN", false),
	REWARD_BET_ROLLBACK("REWARD_BET_ROLLBACK", false),
	REWARD_WIN_ROLLBACK("REWARD_WIN_ROLLBACK", false)
	;

//  Not yet implemented, will be done during bonus rework
//	VIRTUAL_FREE_BET ("VIRTUAL_FREE_BET", false),
//	VIRTUAL_FREE_WIN ("VIRTUAL_FREE_WIN", false),
//	VIRTUAL_FREE_LOSS ("VIRTUAL_FREE_LOSS", false),

	@Setter
	@Getter
	@Accessors(fluent = true)
	private String value;

	@Setter
	@Getter
	@Accessors(fluent = true)
	private boolean bet;

	public String toString() {
		return value;
	}
}
