server:
  port: 9902
  
spring:
  datasource:
    url: jdbc:mysql://localhost/lithium_avatar
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  cloud:
    stream:
      bindings:
        missionstatsoutput:
          group: missionstatsgroup
          binder: rabbit
          destination: missionstatsqueue
          producer:
            required-groups: missionstatsgroup
        userattributestriggerinput :
          group: user-attributes-trigger-group-avatar
          binder : rabbit
          destination : userattributestriggerqueue

lithium:
  services:
    db:
      load-test-data: false
        
logging:
  level:
    lithium.service.avatar: INFO
