package lithium.service.cashier.client.objects;

public enum CashierTranType {
	DEPOSIT ("CASHIER_DEPOSIT"),
	DEPOSIT_FEE ("CASHIER_DEPOSIT_FEE"),
	PAYOUT ("CASHIER_PAYOUT"),
	NEGATIVE_BALANCE_WRITEOFF ("NEGATIVE_BALANCE_WRITEOFF"),
	REVERSAL_FEE ("REVERSAL_FEE"),
	CASHIER_PAYOUT_REVERSAL ("CASHIER_PAYOUT_REVERSAL"),
	CASHIER_DEPOSIT_REVERSAL ("CASHIER_DEPOSIT_REVERSAL"),
	PAYOUT_FEE ("CASHIER_PAYOUT_FEE"),
	PLAYER_BALANCE_PENDING_WITHDRAWAL ("PLAYER_BALANCE_PENDING_WITHDRAWAL"),
	TRANSFER_TO_PLAYER_BALANCE_PENDING_WITHDRAWAL ("TRANSFER_TO_PLAYER_BALANCE_PENDING_WITHDRAWAL"),
	TRANSFER_FROM_PLAYER_BALANCE_PENDING_WITHDRAWAL ("TRANSFER_FROM_PLAYER_BALANCE_PENDING_WITHDRAWAL"),
	TRANSFER_FROM_BALANCE_LIMIT_ESCROW ("TRANSFER_FROM_BALANCE_LIMIT_ESCROW"),
	PLAYER_BALANCE_LIMIT_ESCROW ("PLAYER_BALANCE_LIMIT_ESCROW"),
	MANUAL_CASHIER_ADJUST("MANUAL_CASHIER_ADJUST");

	String value;
	
	CashierTranType(String typeValue) {
		value = typeValue;
	}
	
	public String toString() {
		return value;
	}
	public String value() {
		return value;
	}
}
