server:
  port: 8696

spring:
  application:
    name: service-kyc-provider-onfido
  datasource:
    url: jdbc:mysql://localhost/lithium_kyc_onfido
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  instance:
    appname: service-kyc-provider-onfido
