server.port: 9772

spring:
  application:
    name: service-cashier-processor-pp-etransfer
  cloud:
    stream:
      bindings:
        processorsregisteroutput:
          group: processorsregistergroup
          binder: rabbit
          destination: processorsregisterqueue
          producer:
            required-groups: processorsregistergroup
  thymeleaf:
    cache: false
    
logging:
  level:
    lithium.service.cashier: INFO
    lithium.service.cashier.processor.http: INFO
