.Intervention Casino No More Use Cases
[plantuml]
----
@startuml
skinparam actorStyle awesome

actor Player as p
actor "LBO/DWH" as backoffice

usecase oo as "
Player sends request for casino-no-more.
--
PLAYER_CASINO_BLOCK - Player placed
--
no subordinate type, dwh_visible = false
--
Cannot be removed by player.
Can be removed in LBO.
Can be removed by Auto-Restriction Rules.(if subordinate type was provided)
"
p -> oo


usecase ic as "
LBO adds intervention casino-no-more on player
--
INTERVENTION_CASINO_BLOCK - System Placed
--
subordinate type (not provided=indefinite, else tied to auto-restriction rules), dwh_visible = true
--
Cannot be removed by player.
Can be removed in LBO.
Can be removed by Auto-Restriction Rules.
"
backoffice --> ic
@enduml
----