server.port: 9810

spring:
  application:
    name: service-casino-provider-incentive
  datasource:
    url: jdbc:mysql://localhost/lithium_casino_incentive
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

eureka:
  instance:
    appname: service-casino-provider-incentive

logging:
  level:
    lithium.service.casino.provider.incentive: INFO
