CREATE TABLE `granularity` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `granularity` (`id`, `name`)
VALUES (1, 'GRANULARITY_YEAR'), (2, 'GRANULARITY_MONTH'), (3, 'GRANULARITY_DAY'), (4, 'GRANULARITY_WEEK'), (5, 'GRANULARITY_TOTAL'), (6, 'GRANULARITY_HOUR');
