UPDATE account_code SET code = 'GF_PAYMENT_ERROR' WHERE code = 'PAYMENT_ERROR_GF_USE_ONLY';
UPDATE account_code SET code = 'GF_MISSING_DEPOSIT' WHERE code = 'MISSING_DEPOSIT';
UPDATE account_code SET code = 'GF_MANUAL_BALANCE_ADJUST' WHERE code = 'MANUAL_BALANCE_ADJUST';
UPDATE account_code SET code = 'GF_NEGATIVE_BALANCE_ADJUSTMENT' WHERE code = 'NEGATIVE_BALANCE_ADJUSTMENT';
UPDATE account_code SET code = 'GF_MISSING_WITHDRAWAL' WHERE code = 'MISSING_WITHDRAWAL';
UPDATE account_code SET code = 'GF_MANUAL_BANK_TRANSFER' WHERE code = 'MANUAL_BANK_TRANSFER';
UPDATE account_code SET code = 'GF_FRAUD_CB_ACCOUNT' WHERE code = 'FRAUD_CB_ACCOUNT';
UPDATE account_code SET code = 'GF_CHARGEBACK_RECOVERY' WHERE code = 'CHARGEBACK';
