ALTER TABLE `report_run_results`
ADD COLUMN `email_opt_out` BIT(1) DEFAULT NULL,
ADD COLUMN `sms_opt_out` BIT(1) DEFAULT NULL,
ADD COLUMN `call_opt_out` BIT(1) DEFAULT NULL,
ADD COLUMN `user_id` BIGINT(20) DEFAULT NULL;