.Mass Action Change Status
[plantuml]
----
@startuml
'https://plantuml.com/sequence-diagram

participant  "svc-user-mass-action" as usermassaction
participant "svc-user" as user

alt Perform CHANGE_STATUS action
    usermassaction->user:changeStatus {gateway}/service-user/system/account-status/change
    activate user
    alt success
        user-->usermassaction: Successful Response
    else exception
        user-->usermassaction: Error Response
        deactivate user
        usermassaction->usermassaction: create error_log record (fileData.id, action.id, errorCode, errorMessage)
        note right of usermassaction
            * When an error occurs on a action, then a record will be written to the error_log that provides
              reference back to the player and action being performed

            ErrorCode:
            * a unique it will be based on action being executed.
            ErrorMessage
            * a unique code that gets created per errorMessage
        end note
    end
end

@enduml
----
