spring:
  datasource:
    url: jdbc:mysql://localhost/lithium_sms
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: validate
  cloud:
    stream:
      bindings:
        smsprovidersregisterinput:
          group: smsprovidersregistergroup
          binder: rabbit
          destination: smsprovidersregisterqueue
        smsinput:
          group: smsoutputgroup
          binder: rabbit
          destination: smsoutput
        defaultsmstemplateinput:
          group: default-sms-template-group
          binder: rabbit
          destination: defaultsmstemplateoutput
  rabbitmq:
    listener:
      retry:
        max-attempts: 20
    
logging:
  level:
    lithium.service.sms: INFO
    
server:
  port: 9891

lithium:
  services:
    db:
      load-test-data: false
    sms:
      processing-job-cron: "*/1 * * * * *"
      processing-job-page-size: 10
      sms-error-count-less-than: 1