package com.id3global.id3gws._2013._04;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-10T16:55:59.163+02:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "ID3global",
                  wsdlLocation = "file:/Users/riaans/PSSA/springsource/git/app-lithium-full/service-access/service-access-provider-kycgbg/src/main/resources/wsdl/kyclive.wsdl",
                  targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
public class ID3Global extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.id3global.com/ID3gWS/2013/04", "ID3global");
    public final static QName WsHttpBindingGlobalProfile = new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalProfile");
    public final static QName BasicOAuthHttpBindingGlobalProfile = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicOAuthHttpBinding_GlobalProfile");
    public final static QName WsOAuthHttpBindingGlobalProfile = new QName("http://www.id3global.com/ID3gWS/2013/04", "wsOAuthHttpBinding_GlobalProfile");
    public final static QName BasicHttpBindingGlobalProfile = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalProfile");
    public final static QName BasicHttpBindingGlobalAuthenticate = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalAuthenticate");
    public final static QName BasicOAuthHttpBindingGlobalAuthenticate = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicOAuthHttpBinding_GlobalAuthenticate");
    public final static QName WsOAuthHttpBindingGlobalAuthenticate = new QName("http://www.id3global.com/ID3gWS/2013/04", "wsOAuthHttpBinding_GlobalAuthenticate");
    public final static QName WsHttpBindingGlobalAuthenticate = new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalAuthenticate");
    public final static QName WsHttpBindingGlobalCaseManagement = new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalCaseManagement");
    public final static QName BasicHttpBindingGlobalCaseManagement = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalCaseManagement");
    public final static QName BasicHttpBindingGlobalConfig = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalConfig");
    public final static QName WsHttpBindingGlobalConfig = new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalConfig");
    public final static QName BasicHttpBindingGlobalOrganisation = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalOrganisation");
    public final static QName WsHttpBindingGlobalOrganisation = new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalOrganisation");
    public final static QName BasicHttpBindingGlobalMembership = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalMembership");
    public final static QName WsHttpBindingGlobalMembership = new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalMembership");
    public final static QName BasicHttpBindingGlobalSupplier = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalSupplier");
    public final static QName WsHttpBindingGlobalSupplier = new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalSupplier");
    public final static QName BasicHttpBindingGlobalCredentials = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalCredentials");
    public final static QName WsHttpBindingGlobalCredentials = new QName("http://www.id3global.com/ID3gWS/2013/04", "wsHttpBinding_GlobalCredentials");
    public final static QName BasicHttpBindingGlobalDocImage = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalDocImage");
    public final static QName BasicHttpBindingGlobalSearch = new QName("http://www.id3global.com/ID3gWS/2013/04", "basicHttpBinding_GlobalSearch");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/riaans/PSSA/springsource/git/app-lithium-full/service-access/service-access-provider-kycgbg/src/main/resources/wsdl/kyclive.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ID3Global.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/riaans/PSSA/springsource/git/app-lithium-full/service-access/service-access-provider-kycgbg/src/main/resources/wsdl/kyclive.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ID3Global(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ID3Global(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ID3Global() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ID3Global(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ID3Global(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ID3Global(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalProfile")
    public IGlobalProfile getWsHttpBindingGlobalProfile() {
        return super.getPort(WsHttpBindingGlobalProfile, IGlobalProfile.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalProfile")
    public IGlobalProfile getWsHttpBindingGlobalProfile(WebServiceFeature... features) {
        return super.getPort(WsHttpBindingGlobalProfile, IGlobalProfile.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "basicOAuthHttpBinding_GlobalProfile")
    public IGlobalProfile getBasicOAuthHttpBindingGlobalProfile() {
        return super.getPort(BasicOAuthHttpBindingGlobalProfile, IGlobalProfile.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "basicOAuthHttpBinding_GlobalProfile")
    public IGlobalProfile getBasicOAuthHttpBindingGlobalProfile(WebServiceFeature... features) {
        return super.getPort(BasicOAuthHttpBindingGlobalProfile, IGlobalProfile.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "wsOAuthHttpBinding_GlobalProfile")
    public IGlobalProfile getWsOAuthHttpBindingGlobalProfile() {
        return super.getPort(WsOAuthHttpBindingGlobalProfile, IGlobalProfile.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "wsOAuthHttpBinding_GlobalProfile")
    public IGlobalProfile getWsOAuthHttpBindingGlobalProfile(WebServiceFeature... features) {
        return super.getPort(WsOAuthHttpBindingGlobalProfile, IGlobalProfile.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalProfile")
    public IGlobalProfile getBasicHttpBindingGlobalProfile() {
        return super.getPort(BasicHttpBindingGlobalProfile, IGlobalProfile.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalProfile
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalProfile")
    public IGlobalProfile getBasicHttpBindingGlobalProfile(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingGlobalProfile, IGlobalProfile.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getBasicHttpBindingGlobalAuthenticate() {
        return super.getPort(BasicHttpBindingGlobalAuthenticate, IGlobalAuthenticate.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getBasicHttpBindingGlobalAuthenticate(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingGlobalAuthenticate, IGlobalAuthenticate.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "basicOAuthHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getBasicOAuthHttpBindingGlobalAuthenticate() {
        return super.getPort(BasicOAuthHttpBindingGlobalAuthenticate, IGlobalAuthenticate.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "basicOAuthHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getBasicOAuthHttpBindingGlobalAuthenticate(WebServiceFeature... features) {
        return super.getPort(BasicOAuthHttpBindingGlobalAuthenticate, IGlobalAuthenticate.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "wsOAuthHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getWsOAuthHttpBindingGlobalAuthenticate() {
        return super.getPort(WsOAuthHttpBindingGlobalAuthenticate, IGlobalAuthenticate.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "wsOAuthHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getWsOAuthHttpBindingGlobalAuthenticate(WebServiceFeature... features) {
        return super.getPort(WsOAuthHttpBindingGlobalAuthenticate, IGlobalAuthenticate.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getWsHttpBindingGlobalAuthenticate() {
        return super.getPort(WsHttpBindingGlobalAuthenticate, IGlobalAuthenticate.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalAuthenticate
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalAuthenticate")
    public IGlobalAuthenticate getWsHttpBindingGlobalAuthenticate(WebServiceFeature... features) {
        return super.getPort(WsHttpBindingGlobalAuthenticate, IGlobalAuthenticate.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalCaseManagement
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalCaseManagement")
    public IGlobalCaseManagement getWsHttpBindingGlobalCaseManagement() {
        return super.getPort(WsHttpBindingGlobalCaseManagement, IGlobalCaseManagement.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalCaseManagement
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalCaseManagement")
    public IGlobalCaseManagement getWsHttpBindingGlobalCaseManagement(WebServiceFeature... features) {
        return super.getPort(WsHttpBindingGlobalCaseManagement, IGlobalCaseManagement.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalCaseManagement
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalCaseManagement")
    public IGlobalCaseManagement getBasicHttpBindingGlobalCaseManagement() {
        return super.getPort(BasicHttpBindingGlobalCaseManagement, IGlobalCaseManagement.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalCaseManagement
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalCaseManagement")
    public IGlobalCaseManagement getBasicHttpBindingGlobalCaseManagement(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingGlobalCaseManagement, IGlobalCaseManagement.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalConfig
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalConfig")
    public IGlobalConfig getBasicHttpBindingGlobalConfig() {
        return super.getPort(BasicHttpBindingGlobalConfig, IGlobalConfig.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalConfig
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalConfig")
    public IGlobalConfig getBasicHttpBindingGlobalConfig(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingGlobalConfig, IGlobalConfig.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalConfig
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalConfig")
    public IGlobalConfig getWsHttpBindingGlobalConfig() {
        return super.getPort(WsHttpBindingGlobalConfig, IGlobalConfig.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalConfig
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalConfig")
    public IGlobalConfig getWsHttpBindingGlobalConfig(WebServiceFeature... features) {
        return super.getPort(WsHttpBindingGlobalConfig, IGlobalConfig.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalOrganisation
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalOrganisation")
    public IGlobalOrganisation getBasicHttpBindingGlobalOrganisation() {
        return super.getPort(BasicHttpBindingGlobalOrganisation, IGlobalOrganisation.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalOrganisation
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalOrganisation")
    public IGlobalOrganisation getBasicHttpBindingGlobalOrganisation(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingGlobalOrganisation, IGlobalOrganisation.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalOrganisation
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalOrganisation")
    public IGlobalOrganisation getWsHttpBindingGlobalOrganisation() {
        return super.getPort(WsHttpBindingGlobalOrganisation, IGlobalOrganisation.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalOrganisation
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalOrganisation")
    public IGlobalOrganisation getWsHttpBindingGlobalOrganisation(WebServiceFeature... features) {
        return super.getPort(WsHttpBindingGlobalOrganisation, IGlobalOrganisation.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalMembership
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalMembership")
    public IGlobalMembership getBasicHttpBindingGlobalMembership() {
        return super.getPort(BasicHttpBindingGlobalMembership, IGlobalMembership.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalMembership
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalMembership")
    public IGlobalMembership getBasicHttpBindingGlobalMembership(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingGlobalMembership, IGlobalMembership.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalMembership
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalMembership")
    public IGlobalMembership getWsHttpBindingGlobalMembership() {
        return super.getPort(WsHttpBindingGlobalMembership, IGlobalMembership.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalMembership
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalMembership")
    public IGlobalMembership getWsHttpBindingGlobalMembership(WebServiceFeature... features) {
        return super.getPort(WsHttpBindingGlobalMembership, IGlobalMembership.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalSupplier
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalSupplier")
    public IGlobalSupplier getBasicHttpBindingGlobalSupplier() {
        return super.getPort(BasicHttpBindingGlobalSupplier, IGlobalSupplier.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalSupplier
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalSupplier")
    public IGlobalSupplier getBasicHttpBindingGlobalSupplier(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingGlobalSupplier, IGlobalSupplier.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalSupplier
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalSupplier")
    public IGlobalSupplier getWsHttpBindingGlobalSupplier() {
        return super.getPort(WsHttpBindingGlobalSupplier, IGlobalSupplier.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalSupplier
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalSupplier")
    public IGlobalSupplier getWsHttpBindingGlobalSupplier(WebServiceFeature... features) {
        return super.getPort(WsHttpBindingGlobalSupplier, IGlobalSupplier.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalCredentials
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalCredentials")
    public IGlobalCredentials getBasicHttpBindingGlobalCredentials() {
        return super.getPort(BasicHttpBindingGlobalCredentials, IGlobalCredentials.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalCredentials
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalCredentials")
    public IGlobalCredentials getBasicHttpBindingGlobalCredentials(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingGlobalCredentials, IGlobalCredentials.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalCredentials
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalCredentials")
    public IGlobalCredentials getWsHttpBindingGlobalCredentials() {
        return super.getPort(WsHttpBindingGlobalCredentials, IGlobalCredentials.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalCredentials
     */
    @WebEndpoint(name = "wsHttpBinding_GlobalCredentials")
    public IGlobalCredentials getWsHttpBindingGlobalCredentials(WebServiceFeature... features) {
        return super.getPort(WsHttpBindingGlobalCredentials, IGlobalCredentials.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalDocImage
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalDocImage")
    public IGlobalDocImage getBasicHttpBindingGlobalDocImage() {
        return super.getPort(BasicHttpBindingGlobalDocImage, IGlobalDocImage.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalDocImage
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalDocImage")
    public IGlobalDocImage getBasicHttpBindingGlobalDocImage(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingGlobalDocImage, IGlobalDocImage.class, features);
    }


    /**
     *
     * @return
     *     returns IGlobalSearch
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalSearch")
    public IGlobalSearch getBasicHttpBindingGlobalSearch() {
        return super.getPort(BasicHttpBindingGlobalSearch, IGlobalSearch.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGlobalSearch
     */
    @WebEndpoint(name = "basicHttpBinding_GlobalSearch")
    public IGlobalSearch getBasicHttpBindingGlobalSearch(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingGlobalSearch, IGlobalSearch.class, features);
    }

}
