package com.id3global.id3gws._2013._04;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-10T16:55:59.142+02:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", name = "IGlobalConfig")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck_useraccountlib.ObjectFactory.class})
public interface IGlobalConfig {

    @WebMethod(operationName = "GetLocationCountries", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetLocationCountries")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetLocationCountries", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetLocationCountriesResponse")
    @RequestWrapper(localName = "GetLocationCountries", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetLocationCountriesElement")
    @ResponseWrapper(localName = "GetLocationCountriesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetLocationCountriesResponseElement")
    @WebResult(name = "GetLocationCountriesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalCountryType getLocationCountries()
;

    @WebMethod(operationName = "GetIdentityCardIssuingCountries", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetIdentityCardIssuingCountries")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetIdentityCardIssuingCountries", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetIdentityCardIssuingCountriesResponse")
    @RequestWrapper(localName = "GetIdentityCardIssuingCountries", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetIdentityCardIssuingCountriesElement")
    @ResponseWrapper(localName = "GetIdentityCardIssuingCountriesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetIdentityCardIssuingCountriesResponseElement")
    @WebResult(name = "GetIdentityCardIssuingCountriesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalCountryType getIdentityCardIssuingCountries()
;

    @WebMethod(operationName = "GetPassportCountries", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetPassportCountries")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetPassportCountries", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetPassportCountriesResponse")
    @RequestWrapper(localName = "GetPassportCountries", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPassportCountriesElement")
    @ResponseWrapper(localName = "GetPassportCountriesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPassportCountriesResponseElement")
    @WebResult(name = "GetPassportCountriesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalCountryType getPassportCountries()
;

    @WebMethod(operationName = "GetPEPTiers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetPEPTiers")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetPEPTiers", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetPEPTiersResponse")
    @RequestWrapper(localName = "GetPEPTiers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPEPTiersElement")
    @ResponseWrapper(localName = "GetPEPTiersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPEPTiersResponseElement")
    @WebResult(name = "GetPEPTiersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalPEPTierType getPEPTiers()
;

    @WebMethod(operationName = "GetExtractVersions", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetExtractVersions")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetExtractVersions", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetExtractVersionsResponse")
    @RequestWrapper(localName = "GetExtractVersions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetExtractVersionsElement")
    @ResponseWrapper(localName = "GetExtractVersionsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetExtractVersionsResponseElement")
    @WebResult(name = "GetExtractVersionsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring getExtractVersions()
;

    @WebMethod(operationName = "GetItalyProvinceOfBirth", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetItalyProvinceOfBirth")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetItalyProvinceOfBirth", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetItalyProvinceOfBirthResponse")
    @RequestWrapper(localName = "GetItalyProvinceOfBirth", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetItalyProvinceOfBirthElement")
    @ResponseWrapper(localName = "GetItalyProvinceOfBirthResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetItalyProvinceOfBirthResponseElement")
    @WebResult(name = "GetItalyProvinceOfBirthResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalProvinceType getItalyProvinceOfBirth()
;

    @WebMethod(operationName = "GetSouthAfricaCreditSuppliers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSouthAfricaCreditSuppliers")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSouthAfricaCreditSuppliers", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSouthAfricaCreditSuppliersResponse")
    @RequestWrapper(localName = "GetSouthAfricaCreditSuppliers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSouthAfricaCreditSuppliersElement")
    @ResponseWrapper(localName = "GetSouthAfricaCreditSuppliersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSouthAfricaCreditSuppliersResponseElement")
    @WebResult(name = "GetSouthAfricaCreditSuppliersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalSouthAfricaSupplierType getSouthAfricaCreditSuppliers()
;

    @WebMethod(operationName = "GetIdentityCardNationalityCountries", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetIdentityCardNationalityCountries")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetIdentityCardNationalityCountries", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetIdentityCardNationalityCountriesResponse")
    @RequestWrapper(localName = "GetIdentityCardNationalityCountries", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetIdentityCardNationalityCountriesElement")
    @ResponseWrapper(localName = "GetIdentityCardNationalityCountriesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetIdentityCardNationalityCountriesResponseElement")
    @WebResult(name = "GetIdentityCardNationalityCountriesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalCountryType getIdentityCardNationalityCountries()
;

    @WebMethod(operationName = "SupplierUpdate", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/SupplierUpdate")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/SupplierUpdate", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/SupplierUpdateResponse")
    @RequestWrapper(localName = "SupplierUpdate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SupplierUpdateElement")
    @ResponseWrapper(localName = "SupplierUpdateResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SupplierUpdateResponseElement")
    public void supplierUpdate(

        @WebParam(name = "SupplierName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String supplierName
    );

    @WebMethod(operationName = "GetSearchPurposes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSearchPurposes")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSearchPurposes", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSearchPurposesResponse")
    @RequestWrapper(localName = "GetSearchPurposes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSearchPurposesElement")
    @ResponseWrapper(localName = "GetSearchPurposesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSearchPurposesResponseElement")
    @WebResult(name = "GetSearchPurposesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalSearchPurposeType getSearchPurposes(

        @WebParam(name = "itemcheckID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long itemcheckID
    );

    @WebMethod(operationName = "GetCreditHeaderAccountTypes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCreditHeaderAccountTypes")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCreditHeaderAccountTypes", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCreditHeaderAccountTypesResponse")
    @RequestWrapper(localName = "GetCreditHeaderAccountTypes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCreditHeaderAccountTypesElement")
    @ResponseWrapper(localName = "GetCreditHeaderAccountTypesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCreditHeaderAccountTypesResponseElement")
    @WebResult(name = "GetCreditHeaderAccountTypesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalCreditHeaderAccountTypeType getCreditHeaderAccountTypes()
;

    @WebMethod(operationName = "GetExtractFormats", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetExtractFormats")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetExtractFormats", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetExtractFormatsResponse")
    @RequestWrapper(localName = "GetExtractFormats", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetExtractFormatsElement")
    @ResponseWrapper(localName = "GetExtractFormatsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetExtractFormatsResponseElement")
    @WebResult(name = "GetExtractFormatsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring getExtractFormats()
;

    @WebMethod(operationName = "GetCIFASProductCode", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCIFASProductCode")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCIFASProductCode", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCIFASProductCodeResponse")
    @RequestWrapper(localName = "GetCIFASProductCode", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCIFASProductCodeElement")
    @ResponseWrapper(localName = "GetCIFASProductCodeResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCIFASProductCodeResponseElement")
    @WebResult(name = "GetCIFASProductCodeResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalCIFASProductCodeType getCIFASProductCode()
;

    @WebMethod(operationName = "GetDocImageMaxSizeKBytes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMaxSizeKBytes")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMaxSizeKBytes", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMaxSizeKBytesResponse")
    @RequestWrapper(localName = "GetDocImageMaxSizeKBytes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocImageMaxSizeKBytesElement")
    @ResponseWrapper(localName = "GetDocImageMaxSizeKBytesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocImageMaxSizeKBytesResponseElement")
    @WebResult(name = "GetDocImageMaxSizeKBytesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.Long getDocImageMaxSizeKBytes()
;

    @WebMethod(operationName = "GetDocImageMinHeightResolution", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinHeightResolution")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinHeightResolution", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinHeightResolutionResponse")
    @RequestWrapper(localName = "GetDocImageMinHeightResolution", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocImageMinHeightResolutionElement")
    @ResponseWrapper(localName = "GetDocImageMinHeightResolutionResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocImageMinHeightResolutionResponseElement")
    @WebResult(name = "GetDocImageMinHeightResolutionResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.Long getDocImageMinHeightResolution()
;

    @WebMethod(operationName = "GetSanctionsIssuers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSanctionsIssuers")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSanctionsIssuers", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetSanctionsIssuersResponse")
    @RequestWrapper(localName = "GetSanctionsIssuers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSanctionsIssuersElement")
    @ResponseWrapper(localName = "GetSanctionsIssuersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSanctionsIssuersResponseElement")
    @WebResult(name = "GetSanctionsIssuersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalSanctionsIssuerType getSanctionsIssuers()
;

    @WebMethod(operationName = "GetDocumentTypes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocumentTypes")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocumentTypes", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocumentTypesResponse")
    @RequestWrapper(localName = "GetDocumentTypes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocumentTypesElement")
    @ResponseWrapper(localName = "GetDocumentTypesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocumentTypesResponseElement")
    @WebResult(name = "GetDocumentTypesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring getDocumentTypes()
;

    @WebMethod(operationName = "GetDVLADrivingLicenceEndorsements", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDVLADrivingLicenceEndorsements")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDVLADrivingLicenceEndorsements", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDVLADrivingLicenceEndorsementsResponse")
    @RequestWrapper(localName = "GetDVLADrivingLicenceEndorsements", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDVLADrivingLicenceEndorsementsElement")
    @ResponseWrapper(localName = "GetDVLADrivingLicenceEndorsementsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDVLADrivingLicenceEndorsementsResponseElement")
    @WebResult(name = "GetDVLADrivingLicenceEndorsementsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalDVLADrivingLicenceEndorsementType getDVLADrivingLicenceEndorsements()
;

    @WebMethod(operationName = "GetItemCheckResultCodes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetItemCheckResultCodes")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetItemCheckResultCodes", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetItemCheckResultCodesResponse")
    @RequestWrapper(localName = "GetItemCheckResultCodes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetItemCheckResultCodesElement")
    @ResponseWrapper(localName = "GetItemCheckResultCodesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetItemCheckResultCodesResponseElement")
    @WebResult(name = "GetItemCheckResultCodesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalItemCheckResultCodesType getItemCheckResultCodes(

        @WebParam(name = "ID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long id
    );

    @WebMethod(operationName = "GetCardName", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCardName")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCardName", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetCardNameResponse")
    @RequestWrapper(localName = "GetCardName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCardNameElement")
    @ResponseWrapper(localName = "GetCardNameResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCardNameResponseElement")
    @WebResult(name = "GetCardNameResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.String getCardName(

        @WebParam(name = "CardType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalCardTypeType cardType
    );

    @WebMethod(operationName = "GetDocImageMinSizeKBytes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinSizeKBytes")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinSizeKBytes", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinSizeKBytesResponse")
    @RequestWrapper(localName = "GetDocImageMinSizeKBytes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocImageMinSizeKBytesElement")
    @ResponseWrapper(localName = "GetDocImageMinSizeKBytesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocImageMinSizeKBytesResponseElement")
    @WebResult(name = "GetDocImageMinSizeKBytesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.Long getDocImageMinSizeKBytes()
;

    @WebMethod(operationName = "GetFCRASanctionsIssuers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetFCRASanctionsIssuers")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetFCRASanctionsIssuers", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetFCRASanctionsIssuersResponse")
    @RequestWrapper(localName = "GetFCRASanctionsIssuers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetFCRASanctionsIssuersElement")
    @ResponseWrapper(localName = "GetFCRASanctionsIssuersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetFCRASanctionsIssuersResponseElement")
    @WebResult(name = "GetFCRASanctionsIssuersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalSanctionsIssuerType getFCRASanctionsIssuers()
;

    @WebMethod(operationName = "GetDocImageMinWidthResolution", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinWidthResolution")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinWidthResolution", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageMinWidthResolutionResponse")
    @RequestWrapper(localName = "GetDocImageMinWidthResolution", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocImageMinWidthResolutionElement")
    @ResponseWrapper(localName = "GetDocImageMinWidthResolutionResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocImageMinWidthResolutionResponseElement")
    @WebResult(name = "GetDocImageMinWidthResolutionResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.Long getDocImageMinWidthResolution()
;

    @WebMethod(operationName = "GetDocImageSupportedFileTypes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageSupportedFileTypes")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageSupportedFileTypes", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetDocImageSupportedFileTypesResponse")
    @RequestWrapper(localName = "GetDocImageSupportedFileTypes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocImageSupportedFileTypesElement")
    @ResponseWrapper(localName = "GetDocImageSupportedFileTypesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocImageSupportedFileTypesResponseElement")
    @WebResult(name = "GetDocImageSupportedFileTypesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring getDocImageSupportedFileTypes()
;

    @WebMethod(operationName = "GetLocationStates", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetLocationStates")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetLocationStates", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalConfig/GetLocationStatesResponse")
    @RequestWrapper(localName = "GetLocationStates", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetLocationStatesElement")
    @ResponseWrapper(localName = "GetLocationStatesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetLocationStatesResponseElement")
    @WebResult(name = "GetLocationStatesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalProvinceType getLocationStates()
;
}
