package com.id3global.id3gws._2013._04;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-10T16:55:59.149+02:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", name = "IGlobalMembership")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck_useraccountlib.ObjectFactory.class})
public interface IGlobalMembership {

    @WebMethod(operationName = "GetOrgAdminAccountID", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetOrgAdminAccountID")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetOrgAdminAccountID", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetOrgAdminAccountIDResponse", fault = {@FaultAction(className = IGlobalMembershipGetOrgAdminAccountIDID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetOrgAdminAccountIDID3gExceptionFault")})
    @RequestWrapper(localName = "GetOrgAdminAccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetOrgAdminAccountIDElement")
    @ResponseWrapper(localName = "GetOrgAdminAccountIDResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetOrgAdminAccountIDResponseElement")
    @WebResult(name = "GetOrgAdminAccountIDResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.String getOrgAdminAccountID(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Product", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalProductType product
    ) throws IGlobalMembershipGetOrgAdminAccountIDID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "ResetPassword", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/ResetPassword")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/ResetPassword", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/ResetPasswordResponse", fault = {@FaultAction(className = IGlobalMembershipResetPasswordID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/ResetPasswordID3gExceptionFault")})
    @RequestWrapper(localName = "ResetPassword", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ResetPasswordElement")
    @ResponseWrapper(localName = "ResetPasswordResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ResetPasswordResponseElement")
    public void resetPassword(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountID,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String password
    ) throws IGlobalMembershipResetPasswordID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetRolePermissions", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRolePermissions")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRolePermissions", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRolePermissionsResponse", fault = {@FaultAction(className = IGlobalMembershipGetRolePermissionsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRolePermissionsID3gExceptionFault")})
    @RequestWrapper(localName = "GetRolePermissions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetRolePermissionsElement")
    @ResponseWrapper(localName = "GetRolePermissionsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetRolePermissionsResponseElement")
    @WebResult(name = "GetRolePermissionsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalResourceType getRolePermissions(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "RoleID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String roleID
    ) throws IGlobalMembershipGetRolePermissionsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "SendWelcomeEmail", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/SendWelcomeEmail")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/SendWelcomeEmail", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/SendWelcomeEmailResponse", fault = {@FaultAction(className = IGlobalMembershipSendWelcomeEmailID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/SendWelcomeEmailID3gExceptionFault")})
    @RequestWrapper(localName = "SendWelcomeEmail", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SendWelcomeEmailElement")
    @ResponseWrapper(localName = "SendWelcomeEmailResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SendWelcomeEmailResponseElement")
    public void sendWelcomeEmail(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID
    ) throws IGlobalMembershipSendWelcomeEmailID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetRoleMembers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRoleMembers")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRoleMembers", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRoleMembersResponse", fault = {@FaultAction(className = IGlobalMembershipGetRoleMembersID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRoleMembersID3gExceptionFault")})
    @RequestWrapper(localName = "GetRoleMembers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetRoleMembersElement")
    @ResponseWrapper(localName = "GetRoleMembersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetRoleMembersResponseElement")
    @WebResult(name = "GetRoleMembersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalRoleMembersType getRoleMembers(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "RoleID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String roleID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long filter
    ) throws IGlobalMembershipGetRoleMembersID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateAccountDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateAccountDetails")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateAccountDetails", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateAccountDetailsResponse", fault = {@FaultAction(className = IGlobalMembershipUpdateAccountDetailsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateAccountDetailsID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateAccountDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateAccountDetailsElement")
    @ResponseWrapper(localName = "UpdateAccountDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateAccountDetailsResponseElement")
    public void updateAccountDetails(

        @WebParam(name = "Account", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalAccountDetailsType account
    ) throws IGlobalMembershipUpdateAccountDetailsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CheckNewAccountAgainstPasswordPolicies", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CheckNewAccountAgainstPasswordPolicies")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CheckNewAccountAgainstPasswordPolicies", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CheckNewAccountAgainstPasswordPoliciesResponse", fault = {@FaultAction(className = IGlobalMembershipCheckNewAccountAgainstPasswordPoliciesID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CheckNewAccountAgainstPasswordPoliciesID3gExceptionFault")})
    @RequestWrapper(localName = "CheckNewAccountAgainstPasswordPolicies", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CheckNewAccountAgainstPasswordPoliciesElement")
    @ResponseWrapper(localName = "CheckNewAccountAgainstPasswordPoliciesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CheckNewAccountAgainstPasswordPoliciesResponseElement")
    @WebResult(name = "CheckNewAccountAgainstPasswordPoliciesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.Boolean checkNewAccountAgainstPasswordPolicies(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "RoleIDs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid roleIDs,
        @WebParam(name = "Username", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String username,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String password
    ) throws IGlobalMembershipCheckNewAccountAgainstPasswordPoliciesID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateAccount", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CreateAccount")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CreateAccount", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CreateAccountResponse", fault = {@FaultAction(className = IGlobalMembershipCreateAccountID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CreateAccountID3gExceptionFault")})
    @RequestWrapper(localName = "CreateAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateAccountElement")
    @ResponseWrapper(localName = "CreateAccountResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateAccountResponseElement")
    @WebResult(name = "CreateAccountResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalAccountType createAccount(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String name,
        @WebParam(name = "Username", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String username,
        @WebParam(name = "Email", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String email,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String password,
        @WebParam(name = "PIN", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String pin,
        @WebParam(name = "PasswordNeverExpires", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean passwordNeverExpires,
        @WebParam(name = "RoleIDs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid roleIDs
    ) throws IGlobalMembershipCreateAccountID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateRole", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateRole")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateRole", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateRoleResponse", fault = {@FaultAction(className = IGlobalMembershipUpdateRoleID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateRoleID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateRole", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateRoleElement")
    @ResponseWrapper(localName = "UpdateRoleResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateRoleResponseElement")
    public void updateRole(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Role", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalRoleType role
    ) throws IGlobalMembershipUpdateRoleID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdatePermissions", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdatePermissions")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdatePermissions", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdatePermissionsResponse", fault = {@FaultAction(className = IGlobalMembershipUpdatePermissionsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdatePermissionsID3gExceptionFault")})
    @RequestWrapper(localName = "UpdatePermissions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdatePermissionsElement")
    @ResponseWrapper(localName = "UpdatePermissionsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdatePermissionsResponseElement")
    public void updatePermissions(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ResourceID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String resourceID,
        @WebParam(name = "AddRolePermissions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalRolePermissionType addRolePermissions,
        @WebParam(name = "RemoveRolePermissions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalRolePermissionType removeRolePermissions
    ) throws IGlobalMembershipUpdatePermissionsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetAccountDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountDetails")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountDetails", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountDetailsResponse", fault = {@FaultAction(className = IGlobalMembershipGetAccountDetailsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountDetailsID3gExceptionFault")})
    @RequestWrapper(localName = "GetAccountDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAccountDetailsElement")
    @ResponseWrapper(localName = "GetAccountDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAccountDetailsResponseElement")
    @WebResult(name = "GetAccountDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalAccountDetailsType getAccountDetails(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountID
    ) throws IGlobalMembershipGetAccountDetailsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetAccountPermission", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountPermission")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountPermission", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountPermissionResponse", fault = {@FaultAction(className = IGlobalMembershipGetAccountPermissionID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountPermissionID3gExceptionFault")})
    @RequestWrapper(localName = "GetAccountPermission", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAccountPermissionElement")
    @ResponseWrapper(localName = "GetAccountPermissionResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAccountPermissionResponseElement")
    @WebResult(name = "GetAccountPermissionResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalPermissionType getAccountPermission(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ResourceID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String resourceID
    ) throws IGlobalMembershipGetAccountPermissionID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetRoles", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRoles")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRoles", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRolesResponse", fault = {@FaultAction(className = IGlobalMembershipGetRolesID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetRolesID3gExceptionFault")})
    @RequestWrapper(localName = "GetRoles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetRolesElement")
    @ResponseWrapper(localName = "GetRolesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetRolesResponseElement")
    @WebResult(name = "GetRolesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalRolesType getRoles(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long filter
    ) throws IGlobalMembershipGetRolesID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateRoleMembers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateRoleMembers")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateRoleMembers", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateRoleMembersResponse", fault = {@FaultAction(className = IGlobalMembershipUpdateRoleMembersID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/UpdateRoleMembersID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateRoleMembers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateRoleMembersElement")
    @ResponseWrapper(localName = "UpdateRoleMembersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateRoleMembersResponseElement")
    public void updateRoleMembers(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "RoleID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String roleID,
        @WebParam(name = "AddAccountIDs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid addAccountIDs,
        @WebParam(name = "RemoveAccountIDs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfguid removeAccountIDs
    ) throws IGlobalMembershipUpdateRoleMembersID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetPermissions", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetPermissions")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetPermissions", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetPermissionsResponse", fault = {@FaultAction(className = IGlobalMembershipGetPermissionsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetPermissionsID3gExceptionFault")})
    @RequestWrapper(localName = "GetPermissions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPermissionsElement")
    @ResponseWrapper(localName = "GetPermissionsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPermissionsResponseElement")
    @WebResult(name = "GetPermissionsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalRolePermissionType getPermissions(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ResourceID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String resourceID
    ) throws IGlobalMembershipGetPermissionsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetAccountRoles", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountRoles")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountRoles", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountRolesResponse", fault = {@FaultAction(className = IGlobalMembershipGetAccountRolesID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountRolesID3gExceptionFault")})
    @RequestWrapper(localName = "GetAccountRoles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAccountRolesElement")
    @ResponseWrapper(localName = "GetAccountRolesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAccountRolesResponseElement")
    @WebResult(name = "GetAccountRolesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalRolesType getAccountRoles(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "AccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long filter
    ) throws IGlobalMembershipGetAccountRolesID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateRole", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CreateRole")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CreateRole", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CreateRoleResponse", fault = {@FaultAction(className = IGlobalMembershipCreateRoleID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/CreateRoleID3gExceptionFault")})
    @RequestWrapper(localName = "CreateRole", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateRoleElement")
    @ResponseWrapper(localName = "CreateRoleResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateRoleResponseElement")
    @WebResult(name = "CreateRoleResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalRoleType createRole(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String name,
        @WebParam(name = "Description", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String description,
        @WebParam(name = "IsAdminPolicy", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean isAdminPolicy
    ) throws IGlobalMembershipCreateRoleID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetAccounts", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccounts")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccounts", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountsResponse", fault = {@FaultAction(className = IGlobalMembershipGetAccountsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalMembership/GetAccountsID3gExceptionFault")})
    @RequestWrapper(localName = "GetAccounts", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAccountsElement")
    @ResponseWrapper(localName = "GetAccountsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAccountsResponseElement")
    @WebResult(name = "GetAccountsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalAccountsType getAccounts(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long filter
    ) throws IGlobalMembershipGetAccountsID3GExceptionFaultFaultMessage;
}
