package com.id3global.id3gws._2013._04;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-10T16:55:59.152+02:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", name = "IGlobalSupplier")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck_useraccountlib.ObjectFactory.class})
public interface IGlobalSupplier {

    @WebMethod(operationName = "GetSupplierAccount", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierAccount")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierAccount", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierAccountResponse", fault = {@FaultAction(className = IGlobalSupplierGetSupplierAccountID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierAccountID3gExceptionFault")})
    @RequestWrapper(localName = "GetSupplierAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSupplierAccountElement")
    @ResponseWrapper(localName = "GetSupplierAccountResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSupplierAccountResponseElement")
    @WebResult(name = "GetSupplierAccountResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalSupplierAccountType getSupplierAccount(

        @WebParam(name = "SupplierAccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String supplierAccountID
    ) throws IGlobalSupplierGetSupplierAccountID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "TestSupplierAccountCredentials", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/TestSupplierAccountCredentials")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/TestSupplierAccountCredentials", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/TestSupplierAccountCredentialsResponse", fault = {@FaultAction(className = IGlobalSupplierTestSupplierAccountCredentialsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/TestSupplierAccountCredentialsID3gExceptionFault")})
    @RequestWrapper(localName = "TestSupplierAccountCredentials", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.TestSupplierAccountCredentialsElement")
    @ResponseWrapper(localName = "TestSupplierAccountCredentialsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.TestSupplierAccountCredentialsResponseElement")
    @WebResult(name = "TestSupplierAccountCredentialsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalSupplierAccountType testSupplierAccountCredentials(

        @WebParam(name = "SupplierAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalSupplierAccountType supplierAccount
    ) throws IGlobalSupplierTestSupplierAccountCredentialsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateSupplierAccount", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/UpdateSupplierAccount")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/UpdateSupplierAccount", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/UpdateSupplierAccountResponse", fault = {@FaultAction(className = IGlobalSupplierUpdateSupplierAccountID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/UpdateSupplierAccountID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateSupplierAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateSupplierAccountElement")
    @ResponseWrapper(localName = "UpdateSupplierAccountResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateSupplierAccountResponseElement")
    @WebResult(name = "UpdateSupplierAccountResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalSupplierAccountType updateSupplierAccount(

        @WebParam(name = "SupplierAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalSupplierAccountType supplierAccount
    ) throws IGlobalSupplierUpdateSupplierAccountID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetSupplierAccounts", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierAccounts")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierAccounts", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierAccountsResponse", fault = {@FaultAction(className = IGlobalSupplierGetSupplierAccountsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSupplierAccountsID3gExceptionFault")})
    @RequestWrapper(localName = "GetSupplierAccounts", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSupplierAccountsElement")
    @ResponseWrapper(localName = "GetSupplierAccountsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSupplierAccountsResponseElement")
    @WebResult(name = "GetSupplierAccountsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalSupplierAccountsType getSupplierAccounts(

        @WebParam(name = "SupplierID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String supplierID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long filter
    ) throws IGlobalSupplierGetSupplierAccountsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateSupplier", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/UpdateSupplier")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/UpdateSupplier", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/UpdateSupplierResponse", fault = {@FaultAction(className = IGlobalSupplierUpdateSupplierID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/UpdateSupplierID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateSupplier", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateSupplierElement")
    @ResponseWrapper(localName = "UpdateSupplierResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateSupplierResponseElement")
    public void updateSupplier(

        @WebParam(name = "Supplier", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalSupplierType supplier
    ) throws IGlobalSupplierUpdateSupplierID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetSuppliers", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSuppliers")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSuppliers", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSuppliersResponse", fault = {@FaultAction(className = IGlobalSupplierGetSuppliersID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSupplier/GetSuppliersID3gExceptionFault")})
    @RequestWrapper(localName = "GetSuppliers", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSuppliersElement")
    @ResponseWrapper(localName = "GetSuppliersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSuppliersResponseElement")
    @WebResult(name = "GetSuppliersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalSupplierType getSuppliers()
 throws IGlobalSupplierGetSuppliersID3GExceptionFaultFaultMessage;
}
