package com.id3global.id3gws._2013._04;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-10T16:55:59.122+02:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", name = "IGlobalProfile")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck_useraccountlib.ObjectFactory.class})
public interface IGlobalProfile {

    @WebMethod(operationName = "UpdateProfile", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfile")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfile", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfileResponse", fault = {@FaultAction(className = IGlobalProfileUpdateProfileID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfileID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateProfile", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateProfileElement")
    @ResponseWrapper(localName = "UpdateProfileResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateProfileResponseElement")
    public void updateProfile(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Profile", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalProfileType profile
    ) throws IGlobalProfileUpdateProfileID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateLicenceItemToPending", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateLicenceItemToPending")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateLicenceItemToPending", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateLicenceItemToPendingResponse", fault = {@FaultAction(className = IGlobalProfileUpdateLicenceItemToPendingID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateLicenceItemToPendingID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateLicenceItemToPending", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateLicenceItemToPendingElement")
    @ResponseWrapper(localName = "UpdateLicenceItemToPendingResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateLicenceItemToPendingResponseElement")
    public void updateLicenceItemToPending(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "SupplierAccountID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String supplierAccountID
    ) throws IGlobalProfileUpdateLicenceItemToPendingID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetCardTypesMP", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetCardTypesMP")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetCardTypesMP", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetCardTypesMPResponse", fault = {@FaultAction(className = IGlobalProfileGetCardTypesMPID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetCardTypesMPID3gExceptionFault")})
    @RequestWrapper(localName = "GetCardTypesMP", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCardTypesMPElement")
    @ResponseWrapper(localName = "GetCardTypesMPResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCardTypesMPResponseElement")
    @WebResult(name = "GetCardTypesMPResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalCardTypeType getCardTypesMP(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ProfileIDVersions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalProfileIDVersionType profileIDVersions
    ) throws IGlobalProfileGetCardTypesMPID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetProfiles", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfiles")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfiles", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfilesResponse", fault = {@FaultAction(className = IGlobalProfileGetProfilesID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfilesID3gExceptionFault")})
    @RequestWrapper(localName = "GetProfiles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetProfilesElement")
    @ResponseWrapper(localName = "GetProfilesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetProfilesResponseElement")
    @WebResult(name = "GetProfilesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalProfileType getProfiles(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "IncludeTest", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean includeTest,
        @WebParam(name = "IncludePreEffective", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean includePreEffective,
        @WebParam(name = "IncludeEffective", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean includeEffective,
        @WebParam(name = "IncludeRetired", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean includeRetired
    ) throws IGlobalProfileGetProfilesID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetProfileChain", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileChain")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileChain", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileChainResponse", fault = {@FaultAction(className = IGlobalProfileGetProfileChainID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileChainID3gExceptionFault")})
    @RequestWrapper(localName = "GetProfileChain", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetProfileChainElement")
    @ResponseWrapper(localName = "GetProfileChainResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetProfileChainResponseElement")
    @WebResult(name = "GetProfileChainResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalProfileVersionType getProfileChain(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ProfileID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String profileID,
        @WebParam(name = "IncludeTest", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean includeTest,
        @WebParam(name = "IncludePreEffective", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean includePreEffective,
        @WebParam(name = "IncludeEffective", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean includeEffective,
        @WebParam(name = "IncludeRetired", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean includeRetired
    ) throws IGlobalProfileGetProfileChainID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetProfileDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileDetails")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileDetails", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileDetailsResponse", fault = {@FaultAction(className = IGlobalProfileGetProfileDetailsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileDetailsID3gExceptionFault")})
    @RequestWrapper(localName = "GetProfileDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetProfileDetailsElement")
    @ResponseWrapper(localName = "GetProfileDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetProfileDetailsResponseElement")
    @WebResult(name = "GetProfileDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalProfileDetailsType getProfileDetails(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ProfileID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String profileID,
        @WebParam(name = "Version", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long version,
        @WebParam(name = "Revision", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long revision
    ) throws IGlobalProfileGetProfileDetailsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetItemCheckProperties", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetItemCheckProperties")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetItemCheckProperties", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetItemCheckPropertiesResponse", fault = {@FaultAction(className = IGlobalProfileGetItemCheckPropertiesID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetItemCheckPropertiesID3gExceptionFault")})
    @RequestWrapper(localName = "GetItemCheckProperties", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetItemCheckPropertiesElement")
    @ResponseWrapper(localName = "GetItemCheckPropertiesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetItemCheckPropertiesResponseElement")
    @WebResult(name = "GetItemCheckPropertiesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalPropertyType getItemCheckProperties(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ItemCheckID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long itemCheckID
    ) throws IGlobalProfileGetItemCheckPropertiesID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CopyProfile", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/CopyProfile")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/CopyProfile", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/CopyProfileResponse", fault = {@FaultAction(className = IGlobalProfileCopyProfileID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/CopyProfileID3gExceptionFault")})
    @RequestWrapper(localName = "CopyProfile", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CopyProfileElement")
    @ResponseWrapper(localName = "CopyProfileResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CopyProfileResponseElement")
    @WebResult(name = "CopyProfileResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalProfileDetailsType copyProfile(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ProfileIDVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalProfileIDVersionType profileIDVersion,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String name,
        @WebParam(name = "Description", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String description
    ) throws IGlobalProfileCopyProfileID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateLicence", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateLicence")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateLicence", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateLicenceResponse", fault = {@FaultAction(className = IGlobalProfileUpdateLicenceID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateLicenceID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateLicence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateLicenceElement")
    @ResponseWrapper(localName = "UpdateLicenceResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateLicenceResponseElement")
    public void updateLicence(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Licence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalLicenceType licence
    ) throws IGlobalProfileUpdateLicenceID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetProfileVersionItemIDs", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileVersionItemIDs")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileVersionItemIDs", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileVersionItemIDsResponse", fault = {@FaultAction(className = IGlobalProfileGetProfileVersionItemIDsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileVersionItemIDsID3gExceptionFault")})
    @RequestWrapper(localName = "GetProfileVersionItemIDs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetProfileVersionItemIDsElement")
    @ResponseWrapper(localName = "GetProfileVersionItemIDsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetProfileVersionItemIDsResponseElement")
    @WebResult(name = "GetProfileVersionItemIDsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt getProfileVersionItemIDs(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ProfileIdVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalProfileIDVersionType profileIdVersion
    ) throws IGlobalProfileGetProfileVersionItemIDsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetCardTypes", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetCardTypes")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetCardTypes", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetCardTypesResponse", fault = {@FaultAction(className = IGlobalProfileGetCardTypesID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetCardTypesID3gExceptionFault")})
    @RequestWrapper(localName = "GetCardTypes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCardTypesElement")
    @ResponseWrapper(localName = "GetCardTypesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCardTypesResponseElement")
    @WebResult(name = "GetCardTypesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalCardTypeType getCardTypes(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ProfileIDVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalProfileIDVersionType profileIDVersion
    ) throws IGlobalProfileGetCardTypesID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateProfileState", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfileState")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfileState", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfileStateResponse", fault = {@FaultAction(className = IGlobalProfileUpdateProfileStateID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfileStateID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateProfileState", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateProfileStateElement")
    @ResponseWrapper(localName = "UpdateProfileStateResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateProfileStateResponseElement")
    public void updateProfileState(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ProfileIDVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalProfileIDVersionType profileIDVersion,
        @WebParam(name = "StartDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date endDate
    ) throws IGlobalProfileUpdateProfileStateID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetLicence", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetLicence")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetLicence", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetLicenceResponse", fault = {@FaultAction(className = IGlobalProfileGetLicenceID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetLicenceID3gExceptionFault")})
    @RequestWrapper(localName = "GetLicence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetLicenceElement")
    @ResponseWrapper(localName = "GetLicenceResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetLicenceResponseElement")
    @WebResult(name = "GetLicenceResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalLicenceType getLicence(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID
    ) throws IGlobalProfileGetLicenceID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetRetiringProfiles", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetRetiringProfiles")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetRetiringProfiles", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetRetiringProfilesResponse", fault = {@FaultAction(className = IGlobalProfileGetRetiringProfilesID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetRetiringProfilesID3gExceptionFault")})
    @RequestWrapper(localName = "GetRetiringProfiles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetRetiringProfilesElement")
    @ResponseWrapper(localName = "GetRetiringProfilesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetRetiringProfilesResponseElement")
    @WebResult(name = "GetRetiringProfilesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalProfileDetailsType getRetiringProfiles(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Licence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalLicenceType licence
    ) throws IGlobalProfileGetRetiringProfilesID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "SupportedFields", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/SupportedFields")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/SupportedFields", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/SupportedFieldsResponse", fault = {@FaultAction(className = IGlobalProfileSupportedFieldsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/SupportedFieldsID3gExceptionFault")})
    @RequestWrapper(localName = "SupportedFields", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SupportedFieldsElement")
    @ResponseWrapper(localName = "SupportedFieldsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SupportedFieldsResponseElement")
    @WebResult(name = "SupportedFieldsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalSupportedFieldsType supportedFields(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ProfileIDVersions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalProfileIDVersionType profileIDVersions
    ) throws IGlobalProfileSupportedFieldsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateProfile", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/CreateProfile")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/CreateProfile", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/CreateProfileResponse", fault = {@FaultAction(className = IGlobalProfileCreateProfileID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/CreateProfileID3gExceptionFault")})
    @RequestWrapper(localName = "CreateProfile", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateProfileElement")
    @ResponseWrapper(localName = "CreateProfileResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateProfileResponseElement")
    @WebResult(name = "CreateProfileResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalProfileDetailsType createProfile(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String name,
        @WebParam(name = "Description", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String description,
        @WebParam(name = "ItemIDs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfunsignedInt itemIDs
    ) throws IGlobalProfileCreateProfileID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetProfileVersions", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileVersions")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileVersions", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileVersionsResponse", fault = {@FaultAction(className = IGlobalProfileGetProfileVersionsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/GetProfileVersionsID3gExceptionFault")})
    @RequestWrapper(localName = "GetProfileVersions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetProfileVersionsElement")
    @ResponseWrapper(localName = "GetProfileVersionsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetProfileVersionsResponseElement")
    @WebResult(name = "GetProfileVersionsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalProfileVersionType getProfileVersions(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID
    ) throws IGlobalProfileGetProfileVersionsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateProfileDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfileDetails")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfileDetails", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfileDetailsResponse", fault = {@FaultAction(className = IGlobalProfileUpdateProfileDetailsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalProfile/UpdateProfileDetailsID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateProfileDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateProfileDetailsElement")
    @ResponseWrapper(localName = "UpdateProfileDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateProfileDetailsResponseElement")
    public void updateProfileDetails(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ProfileFull", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalProfileDetailsType profileFull,
        @WebParam(name = "NewVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean newVersion
    ) throws IGlobalProfileUpdateProfileDetailsID3GExceptionFaultFaultMessage;
}
