package com.id3global.id3gws._2013._04;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-10T16:55:59.157+02:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", name = "IGlobalDocImage")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck_useraccountlib.ObjectFactory.class})
public interface IGlobalDocImage {

    @WebMethod(operationName = "ProcessStoredImage", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/ProcessStoredImage")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/ProcessStoredImage", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/ProcessStoredImageResponse", fault = {@FaultAction(className = IGlobalDocImageProcessStoredImageID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/ProcessStoredImageID3gExceptionFault")})
    @RequestWrapper(localName = "ProcessStoredImage", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ProcessStoredImageElement")
    @ResponseWrapper(localName = "ProcessStoredImageResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ProcessStoredImageResponseElement")
    @WebResult(name = "ProcessStoredImageResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalDIVDataType processStoredImage(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ImageID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String imageID,
        @WebParam(name = "Synchronous", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean synchronous
    ) throws IGlobalDocImageProcessStoredImageID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetDocumentExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetDocumentExtract")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetDocumentExtract", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetDocumentExtractResponse", fault = {@FaultAction(className = IGlobalDocImageGetDocumentExtractID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetDocumentExtractID3gExceptionFault")})
    @RequestWrapper(localName = "GetDocumentExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocumentExtractElement")
    @ResponseWrapper(localName = "GetDocumentExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDocumentExtractResponseElement")
    @WebResult(name = "GetDocumentExtractResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public byte[] getDocumentExtract(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "StartDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date endDate,
        @WebParam(name = "SearchType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long searchType,
        @WebParam(name = "SearchValue", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String searchValue,
        @WebParam(name = "Format", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long format
    ) throws IGlobalDocImageGetDocumentExtractID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UploadAndProcess", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/UploadAndProcess")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/UploadAndProcess", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/UploadAndProcessResponse", fault = {@FaultAction(className = IGlobalDocImageUploadAndProcessID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/UploadAndProcessID3gExceptionFault")})
    @RequestWrapper(localName = "UploadAndProcess", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UploadAndProcessElement")
    @ResponseWrapper(localName = "UploadAndProcessResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UploadAndProcessResponseElement")
    @WebResult(name = "UploadAndProcessResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalDIVDataType uploadAndProcess(

        @WebParam(name = "DocImage", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        byte[] docImage
    ) throws IGlobalDocImageUploadAndProcessID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetImageDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImageDetails")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImageDetails", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImageDetailsResponse", fault = {@FaultAction(className = IGlobalDocImageGetImageDetailsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImageDetailsID3gExceptionFault")})
    @RequestWrapper(localName = "GetImageDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetImageDetailsElement")
    @ResponseWrapper(localName = "GetImageDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetImageDetailsResponseElement")
    @WebResult(name = "GetImageDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalImageDetailsType getImageDetails(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ImgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String imgID
    ) throws IGlobalDocImageGetImageDetailsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetImageResults", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImageResults")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImageResults", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImageResultsResponse", fault = {@FaultAction(className = IGlobalDocImageGetImageResultsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImageResultsID3gExceptionFault")})
    @RequestWrapper(localName = "GetImageResults", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetImageResultsElement")
    @ResponseWrapper(localName = "GetImageResultsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetImageResultsResponseElement")
    @WebResult(name = "GetImageResultsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalDIVDataType getImageResults(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String authenticationID
    ) throws IGlobalDocImageGetImageResultsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "Upload", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/Upload")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/Upload", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/UploadResponse", fault = {@FaultAction(className = IGlobalDocImageUploadID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/UploadID3gExceptionFault")})
    @RequestWrapper(localName = "Upload", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UploadElement")
    @ResponseWrapper(localName = "UploadResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UploadResponseElement")
    @WebResult(name = "UploadResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalDIVDataType upload(

        @WebParam(name = "DocImage", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        byte[] docImage
    ) throws IGlobalDocImageUploadID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "StoreDocumentImage", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/StoreDocumentImage")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/StoreDocumentImage", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/StoreDocumentImageResponse", fault = {@FaultAction(className = IGlobalDocImageStoreDocumentImageID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/StoreDocumentImageID3gExceptionFault")})
    @RequestWrapper(localName = "StoreDocumentImage", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.StoreDocumentImageElement")
    @ResponseWrapper(localName = "StoreDocumentImageResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.StoreDocumentImageResponseElement")
    @WebResult(name = "StoreDocumentImageResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.String storeDocumentImage(

        @WebParam(name = "DocImage", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        byte[] docImage
    ) throws IGlobalDocImageStoreDocumentImageID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "DownloadStoredImage", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/DownloadStoredImage")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/DownloadStoredImage", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/DownloadStoredImageResponse", fault = {@FaultAction(className = IGlobalDocImageDownloadStoredImageID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/DownloadStoredImageID3gExceptionFault")})
    @RequestWrapper(localName = "DownloadStoredImage", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.DownloadStoredImageElement")
    @ResponseWrapper(localName = "DownloadStoredImageResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.DownloadStoredImageResponseElement")
    @WebResult(name = "DownloadStoredImageResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public byte[] downloadStoredImage(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ImageID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String imageID
    ) throws IGlobalDocImageDownloadStoredImageID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UploadAndProcessByProfileProperties", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/UploadAndProcessByProfileProperties")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/UploadAndProcessByProfileProperties", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/UploadAndProcessByProfilePropertiesResponse", fault = {@FaultAction(className = IGlobalDocImageUploadAndProcessByProfilePropertiesID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/UploadAndProcessByProfilePropertiesID3gExceptionFault")})
    @RequestWrapper(localName = "UploadAndProcessByProfileProperties", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UploadAndProcessByProfilePropertiesElement")
    @ResponseWrapper(localName = "UploadAndProcessByProfilePropertiesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UploadAndProcessByProfilePropertiesResponseElement")
    @WebResult(name = "UploadAndProcessByProfilePropertiesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalDIVDataType uploadAndProcessByProfileProperties(

        @WebParam(name = "ProfileID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String profileID,
        @WebParam(name = "Version", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long version,
        @WebParam(name = "Revision", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long revision,
        @WebParam(name = "DocImage", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        byte[] docImage
    ) throws IGlobalDocImageUploadAndProcessByProfilePropertiesID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "Download", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/Download")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/Download", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/DownloadResponse", fault = {@FaultAction(className = IGlobalDocImageDownloadID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/DownloadID3gExceptionFault")})
    @RequestWrapper(localName = "Download", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.DownloadElement")
    @ResponseWrapper(localName = "DownloadResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.DownloadResponseElement")
    @WebResult(name = "DownloadResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public byte[] download(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String authenticationID
    ) throws IGlobalDocImageDownloadID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetImages", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImages")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImages", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImagesResponse", fault = {@FaultAction(className = IGlobalDocImageGetImagesID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalDocImage/GetImagesID3gExceptionFault")})
    @RequestWrapper(localName = "GetImages", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetImagesElement")
    @ResponseWrapper(localName = "GetImagesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetImagesResponseElement")
    @WebResult(name = "GetImagesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalImagesType getImages(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "StartDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date endDate,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long pageSize,
        @WebParam(name = "SortType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long sortType,
        @WebParam(name = "DescendingOrder", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean descendingOrder,
        @WebParam(name = "SearchType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String searchType,
        @WebParam(name = "SearchValue", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String searchValue
    ) throws IGlobalDocImageGetImagesID3GExceptionFaultFaultMessage;
}
