package com.id3global.id3gws._2013._04;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-10T16:55:59.159+02:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", name = "IGlobalSearch")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck_useraccountlib.ObjectFactory.class})
public interface IGlobalSearch {

    @WebMethod(operationName = "UpdateAuthenticationHelpdeskAccess", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateAuthenticationHelpdeskAccess")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateAuthenticationHelpdeskAccess", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateAuthenticationHelpdeskAccessResponse", fault = {@FaultAction(className = IGlobalSearchUpdateAuthenticationHelpdeskAccessID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateAuthenticationHelpdeskAccessID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateAuthenticationHelpdeskAccess", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateAuthenticationHelpdeskAccessElement")
    @ResponseWrapper(localName = "UpdateAuthenticationHelpdeskAccessResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateAuthenticationHelpdeskAccessResponseElement")
    public void updateAuthenticationHelpdeskAccess(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String authenticationID,
        @WebParam(name = "Enable", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean enable
    ) throws IGlobalSearchUpdateAuthenticationHelpdeskAccessID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetDataExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtract")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtract", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtractResponse", fault = {@FaultAction(className = IGlobalSearchGetDataExtractID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtractID3gExceptionFault")})
    @RequestWrapper(localName = "GetDataExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDataExtractElement")
    @ResponseWrapper(localName = "GetDataExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDataExtractResponseElement")
    @WebResult(name = "GetDataExtractResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public byte[] getDataExtract(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "StartDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date endDate,
        @WebParam(name = "SearchType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long searchType,
        @WebParam(name = "SearchValue", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String searchValue,
        @WebParam(name = "Format", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long format,
        @WebParam(name = "Version", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String version
    ) throws IGlobalSearchGetDataExtractID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "DownloadExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/DownloadExtract")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/DownloadExtract", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/DownloadExtractResponse", fault = {@FaultAction(className = IGlobalSearchDownloadExtractID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/DownloadExtractID3gExceptionFault")})
    @RequestWrapper(localName = "DownloadExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.DownloadExtractElement")
    @ResponseWrapper(localName = "DownloadExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.DownloadExtractResponseElement")
    @WebResult(name = "DownloadExtractResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public byte[] downloadExtract(

        @WebParam(name = "orgId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgId,
        @WebParam(name = "extractId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String extractId
    ) throws IGlobalSearchDownloadExtractID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetLatestAuthenticationDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetLatestAuthenticationDetails")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetLatestAuthenticationDetails", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetLatestAuthenticationDetailsResponse", fault = {@FaultAction(className = IGlobalSearchGetLatestAuthenticationDetailsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetLatestAuthenticationDetailsID3gExceptionFault")})
    @RequestWrapper(localName = "GetLatestAuthenticationDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetLatestAuthenticationDetailsElement")
    @ResponseWrapper(localName = "GetLatestAuthenticationDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetLatestAuthenticationDetailsResponseElement")
    @WebResult(name = "GetLatestAuthenticationDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalAuthenticationDetailsType getLatestAuthenticationDetails(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String authenticationID
    ) throws IGlobalSearchGetLatestAuthenticationDetailsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateUserAccountExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CreateUserAccountExtract")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CreateUserAccountExtract", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CreateUserAccountExtractResponse", fault = {@FaultAction(className = IGlobalSearchCreateUserAccountExtractID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CreateUserAccountExtractID3gExceptionFault")})
    @RequestWrapper(localName = "CreateUserAccountExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateUserAccountExtractElement")
    @ResponseWrapper(localName = "CreateUserAccountExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateUserAccountExtractResponseElement")
    public void createUserAccountExtract(

        @WebParam(name = "orgId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgId,
        @WebParam(name = "name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String name,
        @WebParam(name = "accountType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        org.datacontract.schemas._2004._07.globalcheck_useraccountlib.EnumsUserAccountType accountType,
        @WebParam(name = "format", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        org.datacontract.schemas._2004._07.globalcheck_useraccountlib.EnumsFormat format
    ) throws IGlobalSearchCreateUserAccountExtractID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateDataExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CreateDataExtract")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CreateDataExtract", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CreateDataExtractResponse", fault = {@FaultAction(className = IGlobalSearchCreateDataExtractID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CreateDataExtractID3gExceptionFault")})
    @RequestWrapper(localName = "CreateDataExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateDataExtractElement")
    @ResponseWrapper(localName = "CreateDataExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateDataExtractResponseElement")
    public void createDataExtract(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String name,
        @WebParam(name = "Type", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalDataExtractTypeType type,
        @WebParam(name = "Start", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date start,
        @WebParam(name = "End", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date end,
        @WebParam(name = "Format", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalDataExtractFormatType format,
        @WebParam(name = "Version", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String version,
        @WebParam(name = "Repeat", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean repeat
    ) throws IGlobalSearchCreateDataExtractID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CancelExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CancelExtract")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CancelExtract", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CancelExtractResponse", fault = {@FaultAction(className = IGlobalSearchCancelExtractID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CancelExtractID3gExceptionFault")})
    @RequestWrapper(localName = "CancelExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CancelExtractElement")
    @ResponseWrapper(localName = "CancelExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CancelExtractResponseElement")
    public void cancelExtract(

        @WebParam(name = "orgId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgId,
        @WebParam(name = "extractId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String extractId
    ) throws IGlobalSearchCancelExtractID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetReports", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReports")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReports", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportsResponse", fault = {@FaultAction(className = IGlobalSearchGetReportsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportsID3gExceptionFault")})
    @RequestWrapper(localName = "GetReports", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetReportsElement")
    @ResponseWrapper(localName = "GetReportsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetReportsResponseElement")
    @WebResult(name = "GetReportsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalReportDetailsType getReports(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ReportFolder", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String reportFolder
    ) throws IGlobalSearchGetReportsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetAuthenticationDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAuthenticationDetails")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAuthenticationDetails", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAuthenticationDetailsResponse", fault = {@FaultAction(className = IGlobalSearchGetAuthenticationDetailsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAuthenticationDetailsID3gExceptionFault")})
    @RequestWrapper(localName = "GetAuthenticationDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAuthenticationDetailsElement")
    @ResponseWrapper(localName = "GetAuthenticationDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAuthenticationDetailsResponseElement")
    @WebResult(name = "GetAuthenticationDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalAuthenticationDetailsType getAuthenticationDetails(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String authenticationID
    ) throws IGlobalSearchGetAuthenticationDetailsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetSupplierExtendedStatusInformation", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetSupplierExtendedStatusInformation")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetSupplierExtendedStatusInformation", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetSupplierExtendedStatusInformationResponse", fault = {@FaultAction(className = IGlobalSearchGetSupplierExtendedStatusInformationID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetSupplierExtendedStatusInformationID3gExceptionFault")})
    @RequestWrapper(localName = "GetSupplierExtendedStatusInformation", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSupplierExtendedStatusInformationElement")
    @ResponseWrapper(localName = "GetSupplierExtendedStatusInformationResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSupplierExtendedStatusInformationResponseElement")
    @WebResult(name = "GetSupplierExtendedStatusInformationResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public org.datacontract.schemas._2004._07.globalcheck.ArrayOfGlobalStatus getSupplierExtendedStatusInformation(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String authenticationID
    ) throws IGlobalSearchGetSupplierExtendedStatusInformationID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetDataExtracts", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtracts")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtracts", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtractsResponse", fault = {@FaultAction(className = IGlobalSearchGetDataExtractsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtractsID3gExceptionFault")})
    @RequestWrapper(localName = "GetDataExtracts", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDataExtractsElement")
    @ResponseWrapper(localName = "GetDataExtractsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDataExtractsResponseElement")
    @WebResult(name = "GetDataExtractsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalDataExtractsType getDataExtracts(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long pageSize,
        @WebParam(name = "Search", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String search,
        @WebParam(name = "Filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long filter
    ) throws IGlobalSearchGetDataExtractsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetFCRAMatchDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetFCRAMatchDetails")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetFCRAMatchDetails", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetFCRAMatchDetailsResponse", fault = {@FaultAction(className = IGlobalSearchGetFCRAMatchDetailsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetFCRAMatchDetailsID3gExceptionFault")})
    @RequestWrapper(localName = "GetFCRAMatchDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetFCRAMatchDetailsElement")
    @ResponseWrapper(localName = "GetFCRAMatchDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetFCRAMatchDetailsResponseElement")
    @WebResult(name = "GetFCRAMatchDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalFCRAMatchDetailsType getFCRAMatchDetails(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "SearchID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String searchID,
        @WebParam(name = "FCRAEnabled", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean fcraEnabled
    ) throws IGlobalSearchGetFCRAMatchDetailsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CancelDataExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CancelDataExtract")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CancelDataExtract", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CancelDataExtractResponse", fault = {@FaultAction(className = IGlobalSearchCancelDataExtractID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/CancelDataExtractID3gExceptionFault")})
    @RequestWrapper(localName = "CancelDataExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CancelDataExtractElement")
    @ResponseWrapper(localName = "CancelDataExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CancelDataExtractResponseElement")
    public void cancelDataExtract(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "DataExtractID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String dataExtractID
    ) throws IGlobalSearchCancelDataExtractID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetReportImage", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportImage")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportImage", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportImageResponse", fault = {@FaultAction(className = IGlobalSearchGetReportImageID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportImageID3gExceptionFault")})
    @RequestWrapper(localName = "GetReportImage", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetReportImageElement")
    @ResponseWrapper(localName = "GetReportImageResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetReportImageResponseElement")
    @WebResult(name = "GetReportImageResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public byte[] getReportImage(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "RequestID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String requestID,
        @WebParam(name = "ImageID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String imageID
    ) throws IGlobalSearchGetReportImageID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetReportParameters", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportParameters")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportParameters", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportParametersResponse", fault = {@FaultAction(className = IGlobalSearchGetReportParametersID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportParametersID3gExceptionFault")})
    @RequestWrapper(localName = "GetReportParameters", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetReportParametersElement")
    @ResponseWrapper(localName = "GetReportParametersResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetReportParametersResponseElement")
    @WebResult(name = "GetReportParametersResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalReportParameterType getReportParameters(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Path", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String path
    ) throws IGlobalSearchGetReportParametersID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateAuthenticationDataDeletion", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateAuthenticationDataDeletion")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateAuthenticationDataDeletion", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateAuthenticationDataDeletionResponse", fault = {@FaultAction(className = IGlobalSearchUpdateAuthenticationDataDeletionID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateAuthenticationDataDeletionID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateAuthenticationDataDeletion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateAuthenticationDataDeletionElement")
    @ResponseWrapper(localName = "UpdateAuthenticationDataDeletionResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateAuthenticationDataDeletionResponseElement")
    public void updateAuthenticationDataDeletion(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String authenticationID,
        @WebParam(name = "Enable", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean enable
    ) throws IGlobalSearchUpdateAuthenticationDataDeletionID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetDetailedInvestigation", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDetailedInvestigation")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDetailedInvestigation", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDetailedInvestigationResponse", fault = {@FaultAction(className = IGlobalSearchGetDetailedInvestigationID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDetailedInvestigationID3gExceptionFault")})
    @RequestWrapper(localName = "GetDetailedInvestigation", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDetailedInvestigationElement")
    @ResponseWrapper(localName = "GetDetailedInvestigationResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDetailedInvestigationResponseElement")
    @WebResult(name = "GetDetailedInvestigationResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.String getDetailedInvestigation(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String authenticationID,
        @WebParam(name = "Entity_ID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String entityID
    ) throws IGlobalSearchGetDetailedInvestigationID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetAccountExtracts", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAccountExtracts")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAccountExtracts", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAccountExtractsResponse", fault = {@FaultAction(className = IGlobalSearchGetAccountExtractsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAccountExtractsID3gExceptionFault")})
    @RequestWrapper(localName = "GetAccountExtracts", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAccountExtractsElement")
    @ResponseWrapper(localName = "GetAccountExtractsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAccountExtractsResponseElement")
    @WebResult(name = "GetAccountExtractsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ExtractDetailsType getAccountExtracts(

        @WebParam(name = "orgId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgId,
        @WebParam(name = "page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long page,
        @WebParam(name = "pageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long pageSize,
        @WebParam(name = "filter", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long filter
    ) throws IGlobalSearchGetAccountExtractsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "DownloadDataExtract", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/DownloadDataExtract")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/DownloadDataExtract", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/DownloadDataExtractResponse", fault = {@FaultAction(className = IGlobalSearchDownloadDataExtractID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/DownloadDataExtractID3gExceptionFault")})
    @RequestWrapper(localName = "DownloadDataExtract", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.DownloadDataExtractElement")
    @ResponseWrapper(localName = "DownloadDataExtractResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.DownloadDataExtractResponseElement")
    @WebResult(name = "DownloadDataExtractResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public byte[] downloadDataExtract(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "DataExtractID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String dataExtractID
    ) throws IGlobalSearchDownloadDataExtractID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetDataExtractHistory", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtractHistory")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtractHistory", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtractHistoryResponse", fault = {@FaultAction(className = IGlobalSearchGetDataExtractHistoryID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetDataExtractHistoryID3gExceptionFault")})
    @RequestWrapper(localName = "GetDataExtractHistory", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDataExtractHistoryElement")
    @ResponseWrapper(localName = "GetDataExtractHistoryResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetDataExtractHistoryResponseElement")
    @WebResult(name = "GetDataExtractHistoryResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalDataExtractDownloadHistoryType getDataExtractHistory(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "DataExtractID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String dataExtractID
    ) throws IGlobalSearchGetDataExtractHistoryID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetUserAccountExtractHistory", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetUserAccountExtractHistory")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetUserAccountExtractHistory", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetUserAccountExtractHistoryResponse", fault = {@FaultAction(className = IGlobalSearchGetUserAccountExtractHistoryID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetUserAccountExtractHistoryID3gExceptionFault")})
    @RequestWrapper(localName = "GetUserAccountExtractHistory", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetUserAccountExtractHistoryElement")
    @ResponseWrapper(localName = "GetUserAccountExtractHistoryResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetUserAccountExtractHistoryResponseElement")
    @WebResult(name = "GetUserAccountExtractHistoryResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfHistoryAccountHistoryType getUserAccountExtractHistory(

        @WebParam(name = "orgId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgId,
        @WebParam(name = "extractId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String extractId
    ) throws IGlobalSearchGetUserAccountExtractHistoryID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetPEPIntelligenceData", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetPEPIntelligenceData")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetPEPIntelligenceData", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetPEPIntelligenceDataResponse", fault = {@FaultAction(className = IGlobalSearchGetPEPIntelligenceDataID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetPEPIntelligenceDataID3gExceptionFault")})
    @RequestWrapper(localName = "GetPEPIntelligenceData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPEPIntelligenceDataElement")
    @ResponseWrapper(localName = "GetPEPIntelligenceDataResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPEPIntelligenceDataResponseElement")
    @WebResult(name = "GetPEPIntelligenceDataResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalPEPIntelligenceDataType getPEPIntelligenceData(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "SanctionID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String sanctionID
    ) throws IGlobalSearchGetPEPIntelligenceDataID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetReport", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReport")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReport", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportResponse", fault = {@FaultAction(className = IGlobalSearchGetReportID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetReportID3gExceptionFault")})
    @RequestWrapper(localName = "GetReport", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetReportElement")
    @ResponseWrapper(localName = "GetReportResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetReportResponseElement")
    @WebResult(name = "GetReportResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public byte[] getReport(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Path", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String path,
        @WebParam(name = "Format", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String format,
        @WebParam(name = "StreamRoot", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String streamRoot,
        @WebParam(name = "PageRoot", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String pageRoot,
        @WebParam(name = "Parameters", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalReportParameterType parameters,
        @WebParam(name = "PageNumber", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer pageNumber
    ) throws IGlobalSearchGetReportID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateDIVDataDeletion", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateDIVDataDeletion")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateDIVDataDeletion", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateDIVDataDeletionResponse", fault = {@FaultAction(className = IGlobalSearchUpdateDIVDataDeletionID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/UpdateDIVDataDeletionID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateDIVDataDeletion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateDIVDataDeletionElement")
    @ResponseWrapper(localName = "UpdateDIVDataDeletionResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateDIVDataDeletionResponseElement")
    public void updateDIVDataDeletion(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "ImageID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String imageID,
        @WebParam(name = "Enable", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean enable
    ) throws IGlobalSearchUpdateDIVDataDeletionID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetAuthentications", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAuthentications")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAuthentications", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAuthenticationsResponse", fault = {@FaultAction(className = IGlobalSearchGetAuthenticationsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetAuthenticationsID3gExceptionFault")})
    @RequestWrapper(localName = "GetAuthentications", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAuthenticationsElement")
    @ResponseWrapper(localName = "GetAuthenticationsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetAuthenticationsResponseElement")
    @WebResult(name = "GetAuthenticationsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalAuthenticationsType getAuthentications(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "StartDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date endDate,
        @WebParam(name = "SearchType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long searchType,
        @WebParam(name = "SearchValue", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String searchValue,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long pageSize,
        @WebParam(name = "SortType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long sortType,
        @WebParam(name = "DescendingOrder", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean descendingOrder
    ) throws IGlobalSearchGetAuthenticationsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetSanctionsEnforcementsData", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetSanctionsEnforcementsData")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetSanctionsEnforcementsData", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetSanctionsEnforcementsDataResponse", fault = {@FaultAction(className = IGlobalSearchGetSanctionsEnforcementsDataID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalSearch/GetSanctionsEnforcementsDataID3gExceptionFault")})
    @RequestWrapper(localName = "GetSanctionsEnforcementsData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSanctionsEnforcementsDataElement")
    @ResponseWrapper(localName = "GetSanctionsEnforcementsDataResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetSanctionsEnforcementsDataResponseElement")
    @WebResult(name = "GetSanctionsEnforcementsDataResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalSanctionsEnforcementDataType getSanctionsEnforcementsData(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "SanctionID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String sanctionID
    ) throws IGlobalSearchGetSanctionsEnforcementsDataID3GExceptionFaultFaultMessage;
}
