package com.id3global.id3gws._2013._04;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-10T16:55:59.154+02:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", name = "IGlobalCredentials")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck_useraccountlib.ObjectFactory.class})
public interface IGlobalCredentials {

    @WebMethod(operationName = "CheckCredentialsWithPIN", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckCredentialsWithPIN")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckCredentialsWithPIN", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckCredentialsWithPINResponse", fault = {@FaultAction(className = IGlobalCredentialsCheckCredentialsWithPINID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckCredentialsWithPINID3gExceptionFault")})
    @RequestWrapper(localName = "CheckCredentialsWithPIN", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CheckCredentialsWithPINElement")
    @ResponseWrapper(localName = "CheckCredentialsWithPINResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CheckCredentialsWithPINResponseElement")
    @WebResult(name = "CheckCredentialsWithPINResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalAccountType checkCredentialsWithPIN(

        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String password,
        @WebParam(name = "PINSequence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String pinSequence
    ) throws IGlobalCredentialsCheckCredentialsWithPINID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "ChangePassword", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePassword")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePassword", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePasswordResponse", fault = {@FaultAction(className = IGlobalCredentialsChangePasswordID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePasswordID3gExceptionFault")})
    @RequestWrapper(localName = "ChangePassword", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ChangePasswordElement")
    @ResponseWrapper(localName = "ChangePasswordResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ChangePasswordResponseElement")
    public void changePassword(

        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String password,
        @WebParam(name = "PINSequence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String pinSequence,
        @WebParam(name = "NewPassword", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String newPassword
    ) throws IGlobalCredentialsChangePasswordID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetPINSequence", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/GetPINSequence")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/GetPINSequence", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/GetPINSequenceResponse", fault = {@FaultAction(className = IGlobalCredentialsGetPINSequenceID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/GetPINSequenceID3gExceptionFault")})
    @RequestWrapper(localName = "GetPINSequence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPINSequenceElement")
    @ResponseWrapper(localName = "GetPINSequenceResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPINSequenceResponseElement")
    @WebResult(name = "GetPINSequenceResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.String getPINSequence(

        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String password
    ) throws IGlobalCredentialsGetPINSequenceID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "ChangePINWithReminder", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePINWithReminder")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePINWithReminder", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePINWithReminderResponse", fault = {@FaultAction(className = IGlobalCredentialsChangePINWithReminderID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePINWithReminderID3gExceptionFault")})
    @RequestWrapper(localName = "ChangePINWithReminder", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ChangePINWithReminderElement")
    @ResponseWrapper(localName = "ChangePINWithReminderResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ChangePINWithReminderResponseElement")
    public void changePINWithReminder(

        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String password,
        @WebParam(name = "PINSequence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String pinSequence,
        @WebParam(name = "NewPIN", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String newPIN,
        @WebParam(name = "Reminder", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String reminder
    ) throws IGlobalCredentialsChangePINWithReminderID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "ForgotAccountForProduct", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotAccountForProduct")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotAccountForProduct", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotAccountForProductResponse", fault = {@FaultAction(className = IGlobalCredentialsForgotAccountForProductID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotAccountForProductID3gExceptionFault")})
    @RequestWrapper(localName = "ForgotAccountForProduct", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ForgotAccountForProductElement")
    @ResponseWrapper(localName = "ForgotAccountForProductResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ForgotAccountForProductResponseElement")
    public void forgotAccountForProduct(

        @WebParam(name = "Email", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String email,
        @WebParam(name = "ProductName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String productName
    ) throws IGlobalCredentialsForgotAccountForProductID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "ChangePIN", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePIN")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePIN", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePINResponse", fault = {@FaultAction(className = IGlobalCredentialsChangePINID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ChangePINID3gExceptionFault")})
    @RequestWrapper(localName = "ChangePIN", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ChangePINElement")
    @ResponseWrapper(localName = "ChangePINResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ChangePINResponseElement")
    public void changePIN(

        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String password,
        @WebParam(name = "PINSequence", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String pinSequence,
        @WebParam(name = "NewPIN", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String newPIN
    ) throws IGlobalCredentialsChangePINID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CheckCredentials", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckCredentials")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckCredentials", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckCredentialsResponse", fault = {@FaultAction(className = IGlobalCredentialsCheckCredentialsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckCredentialsID3gExceptionFault")})
    @RequestWrapper(localName = "CheckCredentials", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CheckCredentialsElement")
    @ResponseWrapper(localName = "CheckCredentialsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CheckCredentialsResponseElement")
    @WebResult(name = "CheckCredentialsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalAccountType checkCredentials(

        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountName,
        @WebParam(name = "Password", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String password
    ) throws IGlobalCredentialsCheckCredentialsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "ForgotPassword", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotPassword")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotPassword", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotPasswordResponse", fault = {@FaultAction(className = IGlobalCredentialsForgotPasswordID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotPasswordID3gExceptionFault")})
    @RequestWrapper(localName = "ForgotPassword", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ForgotPasswordElement")
    @ResponseWrapper(localName = "ForgotPasswordResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ForgotPasswordResponseElement")
    public void forgotPassword(

        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountName
    ) throws IGlobalCredentialsForgotPasswordID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetPasswordPolicyForUser", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/GetPasswordPolicyForUser")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/GetPasswordPolicyForUser", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/GetPasswordPolicyForUserResponse", fault = {@FaultAction(className = IGlobalCredentialsGetPasswordPolicyForUserID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/GetPasswordPolicyForUserID3gExceptionFault")})
    @RequestWrapper(localName = "GetPasswordPolicyForUser", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPasswordPolicyForUserElement")
    @ResponseWrapper(localName = "GetPasswordPolicyForUserResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetPasswordPolicyForUserResponseElement")
    @WebResult(name = "GetPasswordPolicyForUserResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalPasswordPolicyType getPasswordPolicyForUser(

        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountName
    ) throws IGlobalCredentialsGetPasswordPolicyForUserID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "RequestMemorableWordReminder", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/RequestMemorableWordReminder")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/RequestMemorableWordReminder", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/RequestMemorableWordReminderResponse", fault = {@FaultAction(className = IGlobalCredentialsRequestMemorableWordReminderID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/RequestMemorableWordReminderID3gExceptionFault")})
    @RequestWrapper(localName = "RequestMemorableWordReminder", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.RequestMemorableWordReminderElement")
    @ResponseWrapper(localName = "RequestMemorableWordReminderResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.RequestMemorableWordReminderResponseElement")
    public void requestMemorableWordReminder(

        @WebParam(name = "AccountName", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String accountName
    ) throws IGlobalCredentialsRequestMemorableWordReminderID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "ForgotAccount", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotAccount")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotAccount", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotAccountResponse", fault = {@FaultAction(className = IGlobalCredentialsForgotAccountID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/ForgotAccountID3gExceptionFault")})
    @RequestWrapper(localName = "ForgotAccount", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ForgotAccountElement")
    @ResponseWrapper(localName = "ForgotAccountResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ForgotAccountResponseElement")
    public void forgotAccount(

        @WebParam(name = "Email", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String email
    ) throws IGlobalCredentialsForgotAccountID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CheckNonce", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckNonce")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckNonce", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckNonceResponse", fault = {@FaultAction(className = IGlobalCredentialsCheckNonceID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCredentials/CheckNonceID3gExceptionFault")})
    @RequestWrapper(localName = "CheckNonce", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CheckNonceElement")
    @ResponseWrapper(localName = "CheckNonceResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CheckNonceResponseElement")
    @WebResult(name = "CheckNonceResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalAccountType checkNonce(

        @WebParam(name = "Nonce", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String nonce
    ) throws IGlobalCredentialsCheckNonceID3GExceptionFaultFaultMessage;
}
