package com.id3global.id3gws._2013._04;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-10T16:55:59.135+02:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", name = "IGlobalAuthenticate")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck_useraccountlib.ObjectFactory.class})
public interface IGlobalAuthenticate {

    @WebMethod(operationName = "AddressLookup", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AddressLookup")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AddressLookup", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AddressLookupResponse", fault = {@FaultAction(className = IGlobalAuthenticateAddressLookupID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AddressLookupID3gExceptionFault")})
    @RequestWrapper(localName = "AddressLookup", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.AddressLookupElement")
    @ResponseWrapper(localName = "AddressLookupResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.AddressLookupResponseElement")
    @WebResult(name = "AddressLookupResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalAddressType addressLookup(

        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalAddressType inputData
    ) throws IGlobalAuthenticateAddressLookupID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "AuthenticateMP", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AuthenticateMP")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AuthenticateMP", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AuthenticateMPResponse", fault = {@FaultAction(className = IGlobalAuthenticateAuthenticateMPID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AuthenticateMPID3gExceptionFault")})
    @RequestWrapper(localName = "AuthenticateMP", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.AuthenticateMPElement")
    @ResponseWrapper(localName = "AuthenticateMPResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.AuthenticateMPResponseElement")
    @WebResult(name = "AuthenticateMPResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalResultDataType authenticateMP(

        @WebParam(name = "ProfileIDVersions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalProfileIDVersionType profileIDVersions,
        @WebParam(name = "CustomerReference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String customerReference,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalInputDataType inputData
    ) throws IGlobalAuthenticateAuthenticateMPID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "AuthenticateSP", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AuthenticateSP")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AuthenticateSP", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AuthenticateSPResponse", fault = {@FaultAction(className = IGlobalAuthenticateAuthenticateSPID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/AuthenticateSPID3gExceptionFault")})
    @RequestWrapper(localName = "AuthenticateSP", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.AuthenticateSPElement")
    @ResponseWrapper(localName = "AuthenticateSPResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.AuthenticateSPResponseElement")
    @WebResult(name = "AuthenticateSPResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalResultDataType authenticateSP(

        @WebParam(name = "ProfileIDVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalProfileIDVersionType profileIDVersion,
        @WebParam(name = "CustomerReference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String customerReference,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalInputDataType inputData
    ) throws IGlobalAuthenticateAuthenticateSPID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "IncrementalVerification", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/IncrementalVerification")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/IncrementalVerification", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/IncrementalVerificationResponse", fault = {@FaultAction(className = IGlobalAuthenticateIncrementalVerificationID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/IncrementalVerificationID3gExceptionFault")})
    @RequestWrapper(localName = "IncrementalVerification", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.IncrementalVerificationElement")
    @ResponseWrapper(localName = "IncrementalVerificationResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.IncrementalVerificationResponseElement")
    @WebResult(name = "IncrementalVerificationResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalResultDataType incrementalVerification(

        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String authenticationID,
        @WebParam(name = "ProfileIDVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalProfileIDVersionType profileIDVersion,
        @WebParam(name = "CustomerReference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String customerReference,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalInputDataType inputData
    ) throws IGlobalAuthenticateIncrementalVerificationID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "ForceOverride", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/ForceOverride")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/ForceOverride", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/ForceOverrideResponse", fault = {@FaultAction(className = IGlobalAuthenticateForceOverrideID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalAuthenticate/ForceOverrideID3gExceptionFault")})
    @RequestWrapper(localName = "ForceOverride", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ForceOverrideElement")
    @ResponseWrapper(localName = "ForceOverrideResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.ForceOverrideResponseElement")
    @WebResult(name = "ForceOverrideResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalResultDataType forceOverride(

        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String authenticationID,
        @WebParam(name = "ProfileIDVersion", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalProfileIDVersionType profileIDVersion,
        @WebParam(name = "CustomerReference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String customerReference,
        @WebParam(name = "Overrides", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalOverrideType overrides
    ) throws IGlobalAuthenticateForceOverrideID3GExceptionFaultFaultMessage;
}
