package com.id3global.id3gws._2013._04;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-10-10T16:55:59.137+02:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", name = "IGlobalCaseManagement")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck.ObjectFactory.class, org.datacontract.schemas._2004._07.globalcheck_useraccountlib.ObjectFactory.class})
public interface IGlobalCaseManagement {

    @WebMethod(operationName = "GetCaseNotification", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseNotification")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseNotification", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseNotificationResponse", fault = {@FaultAction(className = IGlobalCaseManagementGetCaseNotificationID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseNotificationID3gExceptionFault")})
    @RequestWrapper(localName = "GetCaseNotification", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCaseNotificationElement")
    @ResponseWrapper(localName = "GetCaseNotificationResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCaseNotificationResponseElement")
    @WebResult(name = "GetCaseNotificationResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalCaseNotificationType getCaseNotification(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID
    ) throws IGlobalCaseManagementGetCaseNotificationID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "SaveDocumentResult", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveDocumentResult")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveDocumentResult", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveDocumentResultResponse", fault = {@FaultAction(className = IGlobalCaseManagementSaveDocumentResultID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveDocumentResultID3gExceptionFault")})
    @RequestWrapper(localName = "SaveDocumentResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SaveDocumentResultElement")
    @ResponseWrapper(localName = "SaveDocumentResultResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SaveDocumentResultResponseElement")
    @WebResult(name = "SaveDocumentResultResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalCaseDetailsType saveDocumentResult(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "Results", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalCaseDocumentResultType results,
        @WebParam(name = "Param", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalCaseDocumentResultParametersType param
    ) throws IGlobalCaseManagementSaveDocumentResultID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateDispatchStatus", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateDispatchStatus")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateDispatchStatus", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateDispatchStatusResponse", fault = {@FaultAction(className = IGlobalCaseManagementUpdateDispatchStatusID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateDispatchStatusID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateDispatchStatus", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateDispatchStatusElement")
    @ResponseWrapper(localName = "UpdateDispatchStatusResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateDispatchStatusResponseElement")
    public void updateDispatchStatus(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "Param", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalCaseDispatchParametersType param
    ) throws IGlobalCaseManagementUpdateDispatchStatusID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateCaseNotification", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseNotification")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseNotification", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseNotificationResponse", fault = {@FaultAction(className = IGlobalCaseManagementUpdateCaseNotificationID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseNotificationID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateCaseNotification", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateCaseNotificationElement")
    @ResponseWrapper(localName = "UpdateCaseNotificationResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateCaseNotificationResponseElement")
    public void updateCaseNotification(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "Jobs", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalCaseNotificationJobType jobs
    ) throws IGlobalCaseManagementUpdateCaseNotificationID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "DispatchCase", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/DispatchCase")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/DispatchCase", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/DispatchCaseResponse", fault = {@FaultAction(className = IGlobalCaseManagementDispatchCaseID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/DispatchCaseID3gExceptionFault")})
    @RequestWrapper(localName = "DispatchCase", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.DispatchCaseElement")
    @ResponseWrapper(localName = "DispatchCaseResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.DispatchCaseResponseElement")
    public void dispatchCase(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "Params", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalCaseDispatchParametersType params
    ) throws IGlobalCaseManagementDispatchCaseID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "SaveCaseDocuments", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveCaseDocuments")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveCaseDocuments", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveCaseDocumentsResponse", fault = {@FaultAction(className = IGlobalCaseManagementSaveCaseDocumentsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveCaseDocumentsID3gExceptionFault")})
    @RequestWrapper(localName = "SaveCaseDocuments", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SaveCaseDocumentsElement")
    @ResponseWrapper(localName = "SaveCaseDocumentsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SaveCaseDocumentsResponseElement")
    public void saveCaseDocuments(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "Documents", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalCaseDocumentType documents
    ) throws IGlobalCaseManagementSaveCaseDocumentsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetCaseNotifications", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseNotifications")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseNotifications", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseNotificationsResponse", fault = {@FaultAction(className = IGlobalCaseManagementGetCaseNotificationsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseNotificationsID3gExceptionFault")})
    @RequestWrapper(localName = "GetCaseNotifications", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCaseNotificationsElement")
    @ResponseWrapper(localName = "GetCaseNotificationsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCaseNotificationsResponseElement")
    @WebResult(name = "GetCaseNotificationsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalCaseNotificationsType getCaseNotifications(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long pageSize
    ) throws IGlobalCaseManagementGetCaseNotificationsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetCases", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCases")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCases", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCasesResponse", fault = {@FaultAction(className = IGlobalCaseManagementGetCasesID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCasesID3gExceptionFault")})
    @RequestWrapper(localName = "GetCases", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCasesElement")
    @ResponseWrapper(localName = "GetCasesResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCasesResponseElement")
    @WebResult(name = "GetCasesResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalCasesType getCases(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Page", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long page,
        @WebParam(name = "PageSize", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long pageSize,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String name,
        @WebParam(name = "State", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long state,
        @WebParam(name = "Verdict", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long verdict,
        @WebParam(name = "FromDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.util.Date toDate,
        @WebParam(name = "IncludeDocuments", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean includeDocuments
    ) throws IGlobalCaseManagementGetCasesID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateState", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateState")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateState", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateStateResponse", fault = {@FaultAction(className = IGlobalCaseManagementUpdateStateID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateStateID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateState", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateStateElement")
    @ResponseWrapper(localName = "UpdateStateResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateStateResponseElement")
    public void updateState(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "State", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long state,
        @WebParam(name = "ActionContext", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Long actionContext
    ) throws IGlobalCaseManagementUpdateStateID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetGlobalCaseProfileVersions", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetGlobalCaseProfileVersions")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetGlobalCaseProfileVersions", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetGlobalCaseProfileVersionsResponse", fault = {@FaultAction(className = IGlobalCaseManagementGetGlobalCaseProfileVersionsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetGlobalCaseProfileVersionsID3gExceptionFault")})
    @RequestWrapper(localName = "GetGlobalCaseProfileVersions", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetGlobalCaseProfileVersionsElement")
    @ResponseWrapper(localName = "GetGlobalCaseProfileVersionsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetGlobalCaseProfileVersionsResponseElement")
    @WebResult(name = "GetGlobalCaseProfileVersionsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalCaseProfileVersionType getGlobalCaseProfileVersions(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID
    ) throws IGlobalCaseManagementGetGlobalCaseProfileVersionsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetCustomerSettings", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCustomerSettings")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCustomerSettings", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCustomerSettingsResponse", fault = {@FaultAction(className = IGlobalCaseManagementGetCustomerSettingsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCustomerSettingsID3gExceptionFault")})
    @RequestWrapper(localName = "GetCustomerSettings", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCustomerSettingsElement")
    @ResponseWrapper(localName = "GetCustomerSettingsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCustomerSettingsResponseElement")
    @WebResult(name = "GetCustomerSettingsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalCaseCustomerSettingsType getCustomerSettings(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID
    ) throws IGlobalCaseManagementGetCustomerSettingsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "SaveResult", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveResult")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveResult", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveResultResponse", fault = {@FaultAction(className = IGlobalCaseManagementSaveResultID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveResultID3gExceptionFault")})
    @RequestWrapper(localName = "SaveResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SaveResultElement")
    @ResponseWrapper(localName = "SaveResultResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SaveResultResponseElement")
    @WebResult(name = "SaveResultResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalCaseDetailsType saveResult(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "Results", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalResultDataType results,
        @WebParam(name = "Param", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalCaseResultParametersType param
    ) throws IGlobalCaseManagementSaveResultID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateCase", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/CreateCase")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/CreateCase", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/CreateCaseResponse", fault = {@FaultAction(className = IGlobalCaseManagementCreateCaseID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/CreateCaseID3gExceptionFault")})
    @RequestWrapper(localName = "CreateCase", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateCaseElement")
    @ResponseWrapper(localName = "CreateCaseResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateCaseResponseElement")
    @WebResult(name = "CreateCaseResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.String createCase(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "LinkedAccountId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String linkedAccountId,
        @WebParam(name = "Reference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String reference,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String name,
        @WebParam(name = "State", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer state,
        @WebParam(name = "AuthorType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer authorType,
        @WebParam(name = "ProductId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String productId,
        @WebParam(name = "ActionContext", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer actionContext,
        @WebParam(name = "CustomerReferences", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalCaseReferenceType customerReferences,
        @WebParam(name = "Properties", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalKeyValuePairOfstringstringType properties,
        @WebParam(name = "Profiles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalProfileIDVersionType profiles,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalInputDataType inputData
    ) throws IGlobalCaseManagementCreateCaseID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "CreateFullCase", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/CreateFullCase")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/CreateFullCase", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/CreateFullCaseResponse", fault = {@FaultAction(className = IGlobalCaseManagementCreateFullCaseID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/CreateFullCaseID3gExceptionFault")})
    @RequestWrapper(localName = "CreateFullCase", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateFullCaseElement")
    @ResponseWrapper(localName = "CreateFullCaseResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.CreateFullCaseResponseElement")
    @WebResult(name = "CreateFullCaseResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public java.lang.String createFullCase(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "LinkedAccountId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String linkedAccountId,
        @WebParam(name = "Reference", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String reference,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String name,
        @WebParam(name = "State", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer state,
        @WebParam(name = "AuthorType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer authorType,
        @WebParam(name = "Verdict", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer verdict,
        @WebParam(name = "ProductId", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String productId,
        @WebParam(name = "DisclaimerAccepted", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean disclaimerAccepted,
        @WebParam(name = "ActionContext", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer actionContext,
        @WebParam(name = "CustomerReferences", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalCaseReferenceType customerReferences,
        @WebParam(name = "Properties", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalKeyValuePairOfstringstringType properties,
        @WebParam(name = "Profiles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalProfileIDVersionType profiles,
        @WebParam(name = "DocumentCategorySubmissionTypes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalDocumentCategorySubmissionTypeType documentCategorySubmissionTypes,
        @WebParam(name = "Documents", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalCaseDocumentType documents,
        @WebParam(name = "Consents", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalCaseConsentType consents,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalInputDataType inputData
    ) throws IGlobalCaseManagementCreateFullCaseID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateCustomerSettings", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCustomerSettings")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCustomerSettings", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCustomerSettingsResponse", fault = {@FaultAction(className = IGlobalCaseManagementUpdateCustomerSettingsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCustomerSettingsID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateCustomerSettings", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateCustomerSettingsElement")
    @ResponseWrapper(localName = "UpdateCustomerSettingsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateCustomerSettingsResponseElement")
    public void updateCustomerSettings(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "Settings", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalCaseCustomerSettingsType settings
    ) throws IGlobalCaseManagementUpdateCustomerSettingsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "SaveExternalDataResult", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveExternalDataResult")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveExternalDataResult", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveExternalDataResultResponse", fault = {@FaultAction(className = IGlobalCaseManagementSaveExternalDataResultID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveExternalDataResultID3gExceptionFault")})
    @RequestWrapper(localName = "SaveExternalDataResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SaveExternalDataResultElement")
    @ResponseWrapper(localName = "SaveExternalDataResultResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SaveExternalDataResultResponseElement")
    @WebResult(name = "SaveExternalDataResultResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalCaseDetailsType saveExternalDataResult(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "Param", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalExternalDataResultParametersType param
    ) throws IGlobalCaseManagementSaveExternalDataResultID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "SaveManualDispatchResult", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveManualDispatchResult")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveManualDispatchResult", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveManualDispatchResultResponse", fault = {@FaultAction(className = IGlobalCaseManagementSaveManualDispatchResultID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/SaveManualDispatchResultID3gExceptionFault")})
    @RequestWrapper(localName = "SaveManualDispatchResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SaveManualDispatchResultElement")
    @ResponseWrapper(localName = "SaveManualDispatchResultResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.SaveManualDispatchResultResponseElement")
    @WebResult(name = "SaveManualDispatchResultResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalCaseDetailsType saveManualDispatchResult(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "Param", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalCaseDispatchParametersType param,
        @WebParam(name = "Result", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalDispatchResultType result
    ) throws IGlobalCaseManagementSaveManualDispatchResultID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "RaiseChargingPoint", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/RaiseChargingPoint")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/RaiseChargingPoint", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/RaiseChargingPointResponse", fault = {@FaultAction(className = IGlobalCaseManagementRaiseChargingPointID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/RaiseChargingPointID3gExceptionFault")})
    @RequestWrapper(localName = "RaiseChargingPoint", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.RaiseChargingPointElement")
    @ResponseWrapper(localName = "RaiseChargingPointResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.RaiseChargingPointResponseElement")
    @WebResult(name = "RaiseChargingPointResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalCaseDetailsType raiseChargingPoint(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "ProfileID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String profileID,
        @WebParam(name = "AuthenticationID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String authenticationID
    ) throws IGlobalCaseManagementRaiseChargingPointID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetCaseInputData", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseInputData")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseInputData", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseInputDataResponse", fault = {@FaultAction(className = IGlobalCaseManagementGetCaseInputDataID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseInputDataID3gExceptionFault")})
    @RequestWrapper(localName = "GetCaseInputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCaseInputDataElement")
    @ResponseWrapper(localName = "GetCaseInputDataResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCaseInputDataResponseElement")
    @WebResult(name = "GetCaseInputDataResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalInputDataType getCaseInputData(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID
    ) throws IGlobalCaseManagementGetCaseInputDataID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "RetrieveDispatch", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/RetrieveDispatch")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/RetrieveDispatch", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/RetrieveDispatchResponse", fault = {@FaultAction(className = IGlobalCaseManagementRetrieveDispatchID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/RetrieveDispatchID3gExceptionFault")})
    @RequestWrapper(localName = "RetrieveDispatch", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.RetrieveDispatchElement")
    @ResponseWrapper(localName = "RetrieveDispatchResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.RetrieveDispatchResponseElement")
    public void retrieveDispatch(

        @WebParam(name = "Source", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String source,
        @WebParam(name = "Service", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalCaseDispatchServiceTypeType service
    ) throws IGlobalCaseManagementRetrieveDispatchID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetCaseDetails", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseDetails")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseDetails", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseDetailsResponse", fault = {@FaultAction(className = IGlobalCaseManagementGetCaseDetailsID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseDetailsID3gExceptionFault")})
    @RequestWrapper(localName = "GetCaseDetails", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCaseDetailsElement")
    @ResponseWrapper(localName = "GetCaseDetailsResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCaseDetailsResponseElement")
    @WebResult(name = "GetCaseDetailsResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.GlobalCaseDetailsType getCaseDetails(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID
    ) throws IGlobalCaseManagementGetCaseDetailsID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetCaseAuditRecord", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseAuditRecord")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseAuditRecord", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseAuditRecordResponse", fault = {@FaultAction(className = IGlobalCaseManagementGetCaseAuditRecordID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/GetCaseAuditRecordID3gExceptionFault")})
    @RequestWrapper(localName = "GetCaseAuditRecord", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCaseAuditRecordElement")
    @ResponseWrapper(localName = "GetCaseAuditRecordResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.GetCaseAuditRecordResponseElement")
    @WebResult(name = "GetCaseAuditRecordResult", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
    public com.id3global.id3gws._2013._04.ArrayOfGlobalCaseStateType getCaseAuditRecord(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID
    ) throws IGlobalCaseManagementGetCaseAuditRecordID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateCaseEmail", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseEmail")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseEmail", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseEmailResponse", fault = {@FaultAction(className = IGlobalCaseManagementUpdateCaseEmailID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseEmailID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateCaseEmail", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateCaseEmailElement")
    @ResponseWrapper(localName = "UpdateCaseEmailResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateCaseEmailResponseElement")
    public void updateCaseEmail(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "Email", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String email
    ) throws IGlobalCaseManagementUpdateCaseEmailID3GExceptionFaultFaultMessage;

    @WebMethod(operationName = "UpdateCase", action = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCase")
    @Action(input = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCase", output = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseResponse", fault = {@FaultAction(className = IGlobalCaseManagementUpdateCaseID3GExceptionFaultFaultMessage.class, value = "http://www.id3global.com/ID3gWS/2013/04/IGlobalCaseManagement/UpdateCaseID3gExceptionFault")})
    @RequestWrapper(localName = "UpdateCase", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateCaseElement")
    @ResponseWrapper(localName = "UpdateCaseResponse", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04", className = "com.id3global.id3gws._2013._04.UpdateCaseResponseElement")
    public void updateCase(

        @WebParam(name = "OrgID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String orgID,
        @WebParam(name = "CaseID", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String caseID,
        @WebParam(name = "Name", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.String name,
        @WebParam(name = "State", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer state,
        @WebParam(name = "AuthorType", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer authorType,
        @WebParam(name = "Verdict", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer verdict,
        @WebParam(name = "DisclaimerAccepted", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Boolean disclaimerAccepted,
        @WebParam(name = "ActionContext", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        java.lang.Integer actionContext,
        @WebParam(name = "CustomerReferences", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalCaseReferenceType customerReferences,
        @WebParam(name = "Properties", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalKeyValuePairOfstringstringType properties,
        @WebParam(name = "Profiles", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalProfileIDVersionType profiles,
        @WebParam(name = "DocumentCategorySubmissionTypes", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalDocumentCategorySubmissionTypeType documentCategorySubmissionTypes,
        @WebParam(name = "Documents", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalCaseDocumentType documents,
        @WebParam(name = "Consents", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.ArrayOfGlobalCaseConsentType consents,
        @WebParam(name = "InputData", targetNamespace = "http://www.id3global.com/ID3gWS/2013/04")
        com.id3global.id3gws._2013._04.GlobalInputDataType inputData
    ) throws IGlobalCaseManagementUpdateCaseID3GExceptionFaultFaultMessage;
}
