server:
  port: 9000

#lithium:
#  gateway:
#    httpbin: http://www.google.co.za

#swagger:
#  config:
#    refreshrate: 30000

#eureka:
#  instance:
#    prefer-ip-address: true # registers the service ip rather than the server name
#  client:
#    register-with-eureka: true # register him self at eureka
#    fetch-registry: true # pull down a local copy of the registries
#    service-url:
#      defaultZone: http://localhost:8761/eureka # discovery service location

spring:
  application:
    name: gateway
  cloud:
#    discovery:
#      enabled: true
#    gateway:
#      routes:
#        - id: openapi
#          uri: http://localhost:${server.port}
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs # rewrite open api requests
#        - id: server-oauth2
#          uri: lb://server-oauth2 # netflix eureka correspondent service
#          predicates:
#            - Path=/server-oauth2/** # how we will map the url to the target service
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#          filters:
#            - name: RewritePath
#              args[regexp]: "'/' + serviceId + '/(?<remaining>.*)'"
#              args[replacement]: "'/' + serviceId + '/${remaining}'"
#      routes:
#        - id: openapi
#          uri: http://localhost:${server.port}
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
#springdoc:
#  version: 3.0.0
#  packagesToScan: lithium
#  writer-with-default-pretty-printer: true
#  swagger-ui:
#    disable-swagger-default-url: true
#    urls:
#      - name: server-security
#        url: /server-security/v3/api-docs
#  show-login-endpoint: true
#  show-actuator: false
#  api-docs:
#    groups:
#      enabled: true
logging:
  level:
    org.springframework.cloud.client.discovery: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    reactor.ipc.netty: INFO
    reactor.netty: INFO

management.endpoints.web.exposure.include: '*'