server.port: ${PORT:9108}

spring:
  datasource:
    url: jdbc:mysql://localhost/lithium_report_incomplete_players
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    
lithium:
  services:
    db:
      load-test-data: false
    report:
      players:
        report-run-retry:
          max-number-of-retries: 10
        report-run-restart:
          restart-after-hours: 12
      
logging:
  level:
    lithium.service.report: INFO