server:
  port: 9914
  
spring:
  datasource:
    url: jdbc:mysql://localhost/lithium_reward
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    stream:
      bindings:
        transactiontyperegisteroutput:
          group: transactiontyperegistergroup
          binder: rabbit
          destination: transactiontyperegisterqueue
          producer:
            required-groups: transactiontyperegistergroup
        giverewardinputv1:
          group: giverewardgroupv1
          binder: rabbit
          destination: giverewardqueuev1
        rewardtypeinputv1:
          group: rewardtypegroupv1
          binder: rabbit
          destination: rewardtypequeuev1
        rewardtypeoutputv1:
          group: rewardtypegroupv1
          binder: rabbit
          destination: rewardtypequeuev1
          producer:
            required-groups: rewardtypegroupv1
        register-notification-output:
          binder: rabbit
          destination: register-notification-queue
          producer:
            required-groups: register-notification-trigger-group
        register-notification-type-output:
          binder: rabbit
          destination: register-notification-type-queue
          producer:
            required-groups: register-notification-type-trigger-group

  flyway:
    enabled: true
lithium:
  service:
    reward:
      player-reward-history-page-size: 1000
      player-reward-cancel-page-size: 100
      jobs:
        expiring-rewards-cleanup:
          cron: 0 * * * * *
          page-size: 2000


logging:
  level:
    lithium.leader: WARN
    org.springframework.cloud.netflix.feign: WARN
    lithium.service.reward: INFO

