server:
  port: 9701
spring:
  datasource:
    url: jdbc:mysql://localhost/lithium_user_internal
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  