server.port: 9895

spring:
  application:
    name: service-pushmsg-provider-onesignal
  cloud:
    stream:
      bindings:
        pushmsgprovidersregisteroutput:
          group: pushmsgprovidersregistergroup
          binder: rabbit
          destination: pushmsgprovidersregisterqueue
          producer:
            required-groups: pushmsgprovidersregistergroup

logging:
  level:
    lithium.service.pushmsg: INFO