[plantuml]
----
@startuml

!define p(name, alias) participant "name" as alias << (L,#AAFFCC) >>
!define pn(name, alias) participant "name" as alias << (L,#FFAAAA) >>
!define q(name, alias) queue "name" as alias << (L,#AAFFCC) >>
!define qn(name, alias) queue "name" as alias << (L,#FFAAAA) >>

autonumber

participant "Sports Gateway" as sportsGateway

box "Lithium" #LightSkyBlue
p("service-casino-provider-sportsbook", scpSportsbook)
p("client-service-domain", clientServiceDomain)
end box

activate sportsGateway
sportsGateway -> scpSportsbook: POST \n/bet/reserve \nOR /settle \nOR /settle/credit \nOR /settle/debit

activate scpSportsbook
scpSportsbook -> scpSportsbook: Validate request

scpSportsbook -> scpSportsbook: Validate sha256

scpSportsbook -> clientServiceDomain: Domain setting evaluation

activate clientServiceDomain

note right
DANGEROUS_VB_
MIGRATION_OPEN
_BETS_INGESTION
_WITHOUT_BALANCE
_ADJUST_ENABLED
end note

clientServiceDomain --> scpSportsbook

deactivate clientServiceDomain

alt Enabled
    scpSportsbook --> sportsGateway: 500

else
    scpSportsbook -> scpSportsbook: Proceed with normal workflow
end

deactivate scpSportsbook

deactivate sportsGateway

@enduml
----
[plantuml]