server.port: ${PORT:9455}

spring:
  datasource:
    url: jdbc:mysql://localhost/lithium_affiliate_ia
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: create
      ddl-auto: validate
    
lithium:
  services:
    db:
      load-test-data: false
    report:
      players:
        report-run-retry:
          max-number-of-retries: 10
        report-run-restart:
          restart-fter-hours: 12
      
logging:
  level:
    lithium.service.report: INFO
