= Service User Threshold
Riaan Schoeman <riaan.schoeman@wonderlabz.com>
1.0, January 17, 2023: Service User Threshold
:sectnums:
:doctype: book
:toc: left
:toclevels: 4
:toc-title: svc-user-threshold
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]

This service is used to capture and record thresholds that have been triggered.

[#introduction]
== Introduction
.Overview
[verse]
Everytime a transaction is processed, as part of the flow, we do summaries on accounts for the various granularities.
In this task we will be adding a message onto rabbit to send out a summary of the summaries done. Included with this will be a nett loss for the player for that granularity.
service-user-threshold (new service) will receive those events/messages and compare it to the saved thresholds for a specific type.
If this is the first time that the threshold has been breached for that granularity and the player is marked to receive these warnings (default is true), then a message will be sent to the player inbox, and a record for historical reporting will be saved.
Along with saving this historical record, the set limits and limits used will also be saved.

[#OpenApi]
== OpenApi

* http://localhost:9730/swagger-ui/index.html#/

[#features]
== Features

* Current available flows implemented in the service:

=== xref:./loss-limit-threshold.adoc[Loss Limit Threshold]
=== xref:./deposit-threshold-trigger.adoc[Deposit Threshold Trigger]
=== xref:./loss-limit-visibility-flag.adoc[Loss Limit Visibility Flag]

[#datamodel]
== Data Model

["plantuml",width=100%]
["plantuml",width=100%]
----

include::../../../docs/includes/erd.puml[]

T(domain,domain) {
   pk(id): bigint(20)
   --
   unique(name): varchar(255)
   version: int(11)
}
T(player_threshold_history,player_threshold_history) {
   pk(id): bigint(20)
   --
   amount: decimal(19,2)
   daily_loss_limit: decimal(19,2)
   daily_loss_limit_used: decimal(19,2)
   deposit_amount: decimal(19,2)
   monthly_loss_limit: decimal(19,2)
   monthly_loss_limit_used: decimal(19,2)
   net_lifetime_deposit_amount: decimal(19,2)
   threshold_hit_date: datetime(6)
   version: int(11)
   weekly_loss_limit: decimal(19,2)
   weekly_loss_limit_used: decimal(19,2)
   withdrawal_amount: decimal(19,2)
   fk(threshold_revision_id): bigint(20)
   fk(user_id): bigint(20)
}
T(threshold,threshold) {
   pk(id): bigint(20)
   --
   active: bit(1)
   age_max: int(11)
   age_min: int(11)
   granularity: varchar(255)
   version: int(11)
   fk(current_id): bigint(20)
   fk(domain_id): bigint(20)
   fk(type_id): bigint(20)
}
T(threshold_revision,threshold_revision) {
   pk(id): bigint(20)
   --
   amount: decimal(19,2)
   created_date: datetime(6)
   percentage: decimal(19,2)
   version: int(11)
   fk(created_by_id): bigint(20)
   fk(threshold_id): bigint(20)
}
T(type,type) {
   pk(id): bigint(20)
   --
   unique(name): varchar(255)
   version: int(11)
}
T(user,user) {
   pk(id): bigint(20)
   --
   unique(guid): varchar(255)
   dob_day: int(11)
   dob_month: int(11)
   dob_year: int(11)
   notifications: bit(1)
   test_account: bit(1)
   username: varchar(255)
   version: int(11)
   account_creation_date: datetime(6)
   fk(domain_id): bigint(20)
}

player_threshold_history  }--  threshold_revision       : "threshold_revision_id:id"
player_threshold_history  }--  user                     : "user_id:id"
threshold                 }--  domain                   : "domain_id:id"
threshold                 --{  threshold_revision       : "current_id:id"
threshold                 }--  type                     : "type_id:id"
threshold_revision        --^  threshold                : "threshold_id:id"
threshold_revision        }--  user                     : "created_by_id:id"
user                      }--  domain                   : "domain_id:id"
----

[#sampledata]
== Sample Data
==== Setup Data
.domain
|===
| id | name | version

| 1 | livescore_uk | 0
|===

.type
|===
| id | name | version

| 1 | TYPE_WIN_LIMIT | 0
| 2 | TYPE_LOSS_LIMIT | 0
| 3 | TYPE_DEPOSIT_LIMIT | 0
|===

.threshold
|===
| id | active | age_max | age_min | granularity | version | current_id | domain_id | type_id

| 1 | true | -1 | -1 | GRANULARITY_DAY | 3 | 2 | 1 | 2
| 2 | true | -1 | -1 | GRANULARITY_DAY | 1 | 3 | 1 | 3
|===

.threshold_revision
|===
| id | amount | created_date | percentage | version | created_by_id | threshold_id

| 1 | null | 2023-03-03 09:42:01.979000 | 50.00 | 0 | 2 | 1
| 2 | null | 2023-03-03 09:42:32.673000 | 50.00 | 0 | 2 | 1
| 3 | 50.00 | 2023-03-03 09:43:13.369000 | null | 0 | 2 | 2 

|===

==== Player Data
.user
|===
| id | dob_day | dob_month | dob_year | guid | notifications | test_account | username | version | domain_id | account_creation_date

| 1 | 16 | 6 | 1982 | livescore_uk/951 | true | false | riaans | 1 | 1 | 2023-03-03 09:35:24.558000
|===

.player_threshold_history
|===
| id | amount | daily_loss_limit | daily_loss_limit_used | deposit_amount | monthly_loss_limit | monthly_loss_limit_used | net_lifetime_deposit_amount | threshold_hit_date | version | weekly_loss_limit | weekly_loss_limit_used | withdrawal_amount | threshold_revision_id | user_id 

| 1 | null | 100.00 | 70.00 | null | null | null | null | 2023-03-03 12:17:52.089000 | 0 | null | null | null | 2 | 1 
| 2 | 50.00 | 100.00 | 70.00 | 50.00 | null | null | 1055.00 | 2023-03-03 12:21:38.188000 | 0 | null | null | 0.00 | 3 | 1
|===
