server:
  port: 9926

spring:
  application:
    name: service-promo-provider-casino-iforium

test: win

lithium:
  services:
    db:
      load-test-data: true
        
logging:
  level:
    lithium.leader: WARN
    org.springframework.cloud.netflix.feign.LithiumFeignClientFactoryBean: INFO
    lithium.services.WebRequestInterceptorConfiguration: INFO

