server:
  port: 9925
  
lithium:
  services:
    db:
      load-test-data: true
        
logging:
  level:
    lithium.leader: WARN
    lithium.service.promo.pr.casino.iforium: INFO
    org.springframework.cloud.netflix.feign.LithiumFeignClientFactoryBean: INFO
    lithium.services.WebRequestInterceptorConfiguration: INFO

spring:
  cloud:
    stream:
      bindings:
        missionstatsoutput:
          group: missionstatsgroup
          binder: rabbit
          destination: missionstatsqueue
          producer:
            required-groups: missionstatsgroup