{
 "title": "KYC Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "access-service - uk - verification attempts - gbg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "service-access.*.counter.verification-attempt.livescore_uk.access_service_on_authorize.service-access-provider-kycgbg.*.count"
    }
   ]
  },
  {
   "title": "Verification success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expression": "${smile_pass}/${smile_total} *100",
     "type": "math"
    },
    { "expression": "${gbg_pass}/${gbg_total}*100", "type": "math" },
    {
     "expression": "${gamstop_pass}/${gamstop_total}*100",
     "type": "math"
    },
    {
     "expression": "${sphonic_pass}/${sphonic_total}*100",
     "type": "math"
    }
   ]
  },
  {
   "title": "access-service - uk - verification attempts - gamstop",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "service-access.*.counter.verification-attempt.livescore_uk.access_service_on_authorize.service-access-provider-gamstop.*.count"
    }
   ]
  },
  {
   "title": "access-service - uk -  verification attempts - trans union",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "service-access.*.counter.verification-attempt.livescore_uk.access_service_on_authorize.service-access-provider-transunion.*.count"
    }
   ]
  },
  {
   "title": "kyc-service - ng - verification attempts - Smile identity ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "service-kyc.*.counter.verification-attempt.livescore_nigeria.kyc_service_on_verify.service-kyc-provider-smileidentity.*.count"
    }
   ]
  },
  {
   "title": "access-service - nl -  verification attempts - kyc sphonic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "service-access.*.counter.verification-attempt.livescore_nl.access_service_on_authorize.service-access-provider-sphonic-kyc.*.count"
    }
   ]
  }
 ]
}