server:
  port: 9700
  
spring:
  datasource:
    url: jdbc:mysql://localhost/lithium_user
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.session_factory.interceptor: lithium.service.user.data.interceptors.HibernateInterceptor
      hibernate.jdbc.batch_size: 1000
  cloud:
    stream:
      bindings:
        rolesregisterinput:
          group: rolesregistergroup
          binder: rabbit
          destination: rolesregisterqueue
        usereventsinput:
          binder: rabbit
          destination: usereventsoutput
        registration-success-input :
          group: registration-success-group
          consumer :
            concurrency : 20
            max-concurrency : 40
            prefetch : 1
          binder : rabbit
          destination : registration-success-output
        statsoutputv2:
          group: statsgroupv2
          binder: rabbit
          destination: statsqueuev2
          producer:
            required-groups: statsgroupv2
        missionstatsoutput:
          group: missionstatsgroup
          binder: rabbit
          destination: missionstatsqueue
          producer:
            required-groups: missionstatsgroup
        autorestrictiontriggeroutput:
          group: autorestrictiontriggergroup
          binder: rabbit
          destination: autorestrictiontriggerqueue
          producer:
            required-groups: autorestrictiontriggergroup
        gatewayexchange:
          binder: rabbit
          destination: gateway
          producer:
            should-declare: false
        userattributestriggeroutput:
          binder: rabbit
          destination: userattributestriggerqueue
          producer:
            required-groups:
            - user-attributes-trigger-group-access
            - user-attributes-trigger-group-accounting-internal
            - user-attributes-trigger-group-avatar
            - user-attributes-trigger-group-cashier
            - user-attributes-trigger-group-casino
            - user-attributes-trigger-group-changelog
            - user-attributes-trigger-group-domain
            - user-attributes-trigger-group-event
            - user-attributes-trigger-group-games
            - user-attributes-trigger-group-kyc
            - user-attributes-trigger-group-leaderboard
            - user-attributes-trigger-group-limit
            - user-attributes-trigger-group-mail
            - user-attributes-trigger-group-missions
            - user-attributes-trigger-group-notifications
        service-user-synchronize-output :
          binder : rabbit
          destination : service-user-synchronize-output
          producer :
            required-groups :
              - service-mail-user-synchronize-group
        promotionrestrictiontriggeroutput :
          binder : rabbit
          destination : promotionrestrictiontriggerqueue
          producer :
            required-groups : promotionrestrictiontriggergroup
        vb-migration-input :
          consumer :
            concurrency : 5
            maxAttempts : 5
            backOffInitialInterval : 5000
            backOffMaxInterval : 60000
            backOffMultiplier : 2.5
          group : vb-migration-users-group
          binder : rabbit
          destination : vb-migration-users-queue
        migration-exception-output :
          binder: rabbit
          destination: migration-exception-queue
          producer:
            required-groups: migration-exception-group
        migration-credential-output :
          binder: rabbit
          destination: migration-credential-queue
          producer:
            required-groups: migration-credential-group

      rabbit:
        bindings:
          vb-migration-input:
            consumer:
              autoBindDlq: true
              requeueRejected: true
              republishToDlq: true
  servlet:
    multipart:
        maxFileSize: 20MB
        maxRequestSize: 20MB
        file-size-threshold: 1MB
   
lithium:
  endpoint:
    user-list:
      block: false
  block:
    endpoint: false
  password:
    salt: Pl@yS@feS@-7613D14F-AFF0-47D5-B36F-9B4F5F2DEE4B
  services:
    db:
      load-test-data: false
    user:
      #login-block-failure:
        # milliseconds interval for login failures to be counted
      #  interval-ms: 600000
        # number of times login failure is allowed before blocking
      #  threshold: 5
      public-api-authorizations:
        - id: 3BEF655247BCE7D9B67CD955EB381
          secret-key: 1E19FE349E98741C62CE6E9EBECBC
      password-reset-token:
        cron: 0,15,30,45 * * * * *
        keepAlive: 60
      remove-phone-leading-zero-job:
        cron : 0,5 * * * * *
        keepAlive : 60
      email-validation-token:
        cron: 0,15,30,45 * * * * *
        keepAlive: 60
      user-event:
        keep-alive: 160
      session-inactivity-timeout-job:
        cron : 0,5 * * * * *
        fetch-size: 1000
        no-last-activity-enabled: false # There are no more successful sessions with no last_activity timestamp, we can safely turn this default off.
      referral-flag:
        enabled: false
      jobs:
        pending-playtime-limit-cleanup:
          cron: 0 0/1 * * * *
          page-size: 1000
        opt-out-update:
          cron: 0 0/2 * * * *
          page-size: 10
        geo-names-update:
          fixedRate-in-milliseconds: 60000
          enabled: true
          page-size: 100
      # The override-geo-data config can be used to modify geo data for the following fields i.e country, adminLevel1 and city
      # For example override-geo-data: {"country|IE" : "Ireland","adminLevel1|IE.L" : "Leinster", "city|3369157" : "Dublin"}
      override-geo-data: {
        "country|IE" : "Ireland"
      }
logging:
  level:
    lithium.service.user: INFO
#    org.springframework.cache: INFO
#    org.hibernate.stat: INFO
#    org.hibernate: INFO
#    org.hibernate.type: INFO
#    org.hibernate.type.descriptor.sql: INFO
