server.port: 9717

spring:
  application:
    name: service-cashier-processor-checkout-paypal
  cloud:
    stream:
      bindings:
        processorsregisteroutput:
          group: processorsregistergroup
          binder: rabbit
          destination: processorsregisterqueue
          producer:
            required-groups: processorsregistergroup
  thymeleaf:
    cache: false
logging:
  level:
    lithium.service.cashier: INFO
    lithium.service.cashier.processor: INFO
    lithium.service.cashier.processor.http: INFO
    lithium.service.cashier.processor.checkout.cc: INFO

