server:
  port: 9604

spring:
 application:
   name: service-access-provider-sphonic-kyc
 datasource:
   url: jdbc:mysql://localhost/lithium_access_pr_sphonic_kyc
   username: root
   password: mysql
 jpa:
   show-sql: false
   hibernate:
     ddl-auto: validate
     properties:
       hibernate:
        format_sql: true
   
eureka:
  instance:
    appname: service-access-provider-sphonic-kyc

logging:
  level:
    lithium.service.access.provider.sphonic: INFO
#    lithium.rest: INFO

