server.port: 9627

spring:
  application:
    name: service-cashier-processor-nuvei-cc
  cloud:
    stream:
      bindings:
        processorsregisteroutput:
          group: processorsregistergroup
          binder: rabbit
          destination: processorsregisterqueue
          producer:
            required-groups: processorsregistergroup
  thymeleaf:
    cache: false

logging:
  level:
    lithium.service.cashier: DEBUG
    lithium.service.cashier.processor: DEBUG
    lithium.service.cashier.processor.http: DEBUG
    lithium.service.cashier.processor.nuvei.cc: DEBUG
#    lithium.service.cashier.processor.nuvei.cc.services.NuveiCCUserPaymentMethodService: TRACE
#    com.safecharge: DEBUG
