ALTER TABLE `external_list` ADD COLUMN `timeout_message` VARCHAR(255) DEFAULT NULL, ALGORITHM INPLACE, LOCK NONE;
ALTER TABLE `external_list` ADD COLUMN `review_message` VARCHAR(255) DEFAULT NULL, ALGORITHM INPLACE, LOCK NONE;
