server.port: ${PORT:9207}

spring:
  application:
    name: service-accounting-provider-readonly-secondary
  datasource:
    url: jdbc:mysql://localhost/lithium_accounting_internal
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false

lithium:
  is-read-only: true
  is-summaries-only: false
  can-be-leader-candidate: false

logging:
  level:
    ROOT: WARN