server:
  port: 9901
  
spring:
  datasource:
    url: jdbc:mysql://localhost/lithium_xp
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  cloud:
    stream:
      bindings:
        missionstatsoutput:
          group: missionstatsgroup
          binder: rabbit
          destination: missionstatsqueue
          producer:
            required-groups: missionstatsgroup
        triggerbonusoutput:
          group: triggerbonusgroup
          binder: rabbit
          destination: triggerbonusqueue
          producer:
            required-groups: triggerbonusgroup
        gatewayexchange:
          binder: rabbit
          destination: gateway
          producer:
            should-declare: false
lithium:
  services:
    db:
      load-test-data: false
        
logging:
  level:
    lithium.service.xp: INFO
