server:
  port: 0

spring:
 application:
   name: service-kyc-provider-paystack
   
eureka:
  instance:
    appname: service-kyc-provider-paystack
    
lithium:
  services:
    kyc:
      paystack:
        connection-timeout: 0
        read-timeout:  0