server:
  port: 9919
  
lithium:
  services:
    db:
      load-test-data: true
        
logging:
  level:
    lithium.service.promo.pr.casino.roxor: INFO
spring:
  cloud:
    stream:
      bindings:
        missionstatsoutput:
          group: missionstatsgroup
          binder: rabbit
          destination: missionstatsqueue
          producer:
            required-groups: missionstatsgroup