.promo-stats-group-db
[plantuml]
----

@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "svc-promo" as sb {
  service-promo / service-missions
}

sb --> "lithium_promo"

database "lithium_promo" {
  mission_stat ||--|{ mission_stat_entry
  mission_stat }|--|| user
  mission_stat }|--|| mission_stat_aux_group
  mission_stat_summary }|--|| mission_stat
  mission_stat_summary }|--|| period
  mission_stat_summary }|--|| user
  mission_stat_aux_group }|--|| mission_stat_aux_group_label_values
  mission_stat_aux_group_label_values ||--|| label_value
  label_value ||--|| label

  class mission_stat {
      +`id` bigint(20) NOT NULL AUTO_INCREMENT,
      `action` varchar(255) NOT NULL,
'      `identifier` varchar(255) DEFAULT NULL,
      `name` varchar(255) NOT NULL,
      `type` varchar(255) NOT NULL,
      `version` int(11) NOT NULL,
      `owner_id` bigint(20) NOT NULL
  }

  class mission_stat_entry {
    +`id` bigint(20) NOT NULL AUTO_INCREMENT,
    `entry_date` datetime DEFAULT NULL,
    `value` bigint(20) NOT NULL,
    `version` int(11) NOT NULL,
    `mission_stat_id` bigint(20) NOT NULL
  }

  class mission_stat_summary {
    +`id` bigint(20) NOT NULL AUTO_INCREMENT,
    `version` int(11) NOT NULL,
    `mission_stat_id` bigint(20) NOT NULL,
    `owner_id` bigint(20) NOT NULL,
    `period_id` bigint(20) NOT NULL,
    `value` bigint(20) NOT NULL
'    KEY `FK4g8542tycd1h0en9pu97sp5om` (`mission_stat_id`),
'    KEY `FKo16efnha1acf775tcfvkddnhe` (`owner_id`),
'    KEY `FKhmsjptn7t88b52x9b6vif12wq` (`period_id`),
  }

  class mission_stat_aux_group {
    +`id` bigint(20) NOT NULL AUTO_INCREMENT,
    `version` int(11) NOT NULL,
    `mission_stat_id` bigint(20) NOT NULL,
  }

  class mission_stat_aux_group_label_values {
    +`mission_stat_aux_group_id` bigint(20) NOT NULL,
    +`label_values_id` bigint(20) NOT NULL,
  }

  class label_value {
    +`id` bigint(20) NOT NULL AUTO_INCREMENT,
    `value` varchar(255) DEFAULT NULL,
    `version` int(11) NOT NULL,
    `label_id` bigint(20) NOT NULL,
  }

  class label {
    +`id` bigint(20) NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `version` int(11) NOT NULL,
  }

  class period {
      +`id` bigint(20) NOT NULL AUTO_INCREMENT,
      `date_end` datetime NOT NULL,
      `date_start` datetime NOT NULL,
      `day` int(11) NOT NULL,
      `granularity` int(11) NOT NULL,
      `hour` int(11) NOT NULL,
      `month` int(11) NOT NULL,
      `version` int(11) NOT NULL,
      `week` int(11) NOT NULL,
      `year` int(11) NOT NULL,
      `domain_id` bigint(20) NOT NULL
  }

  class user {
      +`id` bigint(20) NOT NULL AUTO_INCREMENT,
      `guid` varchar(255) NOT NULL,
      `timezone` varchar(255) DEFAULT NULL,
      `version` int(11) NOT NULL,
      `test_account` bit(1) DEFAULT b'0'
  }
}

@enduml

----