server:
  port: 10000

spring:
 application:
   name: service-access-mock-gamstop

logging:
  level:
    lithium.service.access.mock.gamstop: INFO
eureka:
  instance:
    appname: service-access-mock-gamstop
springdoc:
  packagesToScan: lithium.service.mock.gamstop.api

