= LSPLAT-11328 PLAT-12499 ⁃ VB migration user password management
Reza Khan <reza.khan@wonderlabz.com>
1.0, Mar 14, 2023:: TA - LSPLAT-11328 PLAT-12499 ⁃ VB migration user password management
:sectnums:
:toc: left
:toclevels: 4
:toc-title: LSPLAT-11328 PLAT-12499
:icons: font
:source-highlighter: coderay
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
:table-caption!:

WARNING: You might need to install graphviz to render the component models on IntelliJ on plantUML if not viewed on GitLab- see https://playsafe.atlassian.net/wiki/spaces/LITHIUM/pages/1674936347/How+To+Setup+Lithium+Local+Development#Noteworthy-Extensions.1[IntelliJ: PlantUML diagramming tool]

== Description
=== Jira
* https://livescoregroup.atlassian.net/browse/PLAT-12499
* https://playsafe.atlassian.net/browse/LSPLAT-11328

=== Gitlab
* Branch: origin/feature/LSPLAT-11328-VB-migration-user-password-management
* MR: https://gitlab.com/playsafe/lithium/app-lithium-full/-/merge_requests/6246

=== Business
Post migration to lithium, players need to be able to continue authenticating their accounts using their credentials.

=== Approvals
|===
|Component |Reason |Comments

|Li
|
|

|DWH
|
|

|===

== Architecture
=== Technical
For password hashing, DK uses SHA1 and PBKDF2 hash algorithms. Each player's password hash is calculated using one of these two. Additionally, each player has a unique salt.

The password verification process in lithium will need to be altered to cater for this.

==== Analysis of required data from DK
Hash algorithm, salt, and hashed password is stored on the user level.

|===
|Value (PasswordHashingAlgorithm) |Hash Algorithm

|null
|SHA-1

|0
|SHA-1

|1
|PBKDF2
|===

==== lithium_user modifications
include::../plantuml/erd/vb-migration-user-password-management-erd.puml[]

* The hashed password to be saved as is to lithium_user.user.password_hash (existing.)
* New table to be added, lithium_user.user_password_hash_algorithm. On migration of users, the hash algorithm and salt retrieved from DK to be stored here.
* hash_algorithm field to be an integer. In code, translated to applicable enum.

==== Login flow (basic low level.)
include::../plantuml/sequence/vb-migration-user-password-management-login-sequence.puml[]

==== Password change
* On a password change request, use the regular lithium flow for password update and hashing, and delete record from lithium_user.user_password_hash_algorithm if exists.
* Important to ensure that the record has deleted successfully. If not, the password change request has to be denied.
